modules:
  # Module names must exactly match what the HTTP workflow handler is looking for
  - name: httpServer  # This exact name is required by the HTTP workflow handler
    type: http.server
    config:
      address: ":8080"

  - name: httpRouter  # This exact name is required by the HTTP workflow handler
    type: http.router
    dependsOn: [httpServer]

  - name: authMiddleware
    type: http.middleware.auth
    config:
      secretKey: "example-secret-key" 

  - name: messageBroker
    type: messaging.broker
    config:
      description: "Message broker for multi-workflow example"

  - name: userService
    type: http.handler
    config:
      contentType: "application/json"

  - name: notificationService
    type: messaging.handler
    config:
      description: "Notification service handler"

workflows:
  http:
    routes:
      - path: /api/users
        method: GET
        middlewares: [authMiddleware]
        handler: userService
        
  messaging:
    subscriptions:
      - topic: user-events
        handler: notificationService
    producers:
      - name: userService
        forwardTo: 
          - user-events