modules:
  - name: httpServer
    type: http.Server
    config:
      port: 8080

  - name: router
    type: http.Router
    dependsOn: [httpServer]

  - name: authMiddleware
    type: auth.JWT
    config:
      secretKey: ${ENV_SECRET_KEY}

  - name: messageBroker
    type: messaging.Kafka
    config:
      bootstrapServers: localhost:9092

  - name: userService
    type: service.User
    dependsOn: [authMiddleware]

workflows:
  http:
    routes:
      - path: /api/users
        method: GET
        middleware: [authMiddleware]
        handler:
          module: userService
          method: ListUsers
        response:
          success: 200
          error: 500

  messaging:
    topics:
      - name: user-events
        producers:
          - module: userService
            events: [UserCreated, UserUpdated]
        consumers:
          - module: notificationService
            handler: ProcessUserEvent