requires:
  plugins:
    - name: pipeline-steps
    - name: workflow-plugin-http

modules:
  - name: api-server
    type: http.server
    config:
      address: ":8080"

  - name: router
    type: http.router
    dependsOn: [api-server]

workflows:
  http:
    router: router
    server: api-server
    routes: []

pipelines:
  create-order:
    trigger:
      type: http
      config:
        path: /api/orders
        method: POST
    steps:
      - name: parse-body
        type: step.request_parse
        config:
          fields: ["user_id", "amount", "items"]
      - name: set-defaults
        type: step.set
        config:
          values:
            status: "pending"
            created_at: "{{now}}"
      - name: save-order
        type: step.db_exec
        config:
          database: main-db
          query: "INSERT INTO orders (user_id, amount, status) VALUES ($1, $2, $3)"
          params: ["{{parse-body.user_id}}", "{{parse-body.amount}}", "{{set-defaults.status}}"]
      - name: respond
        type: step.json_response
        config:
          status: 201
          body:
            message: "Order created"

  list-orders:
    trigger:
      type: http
      config:
        path: /api/orders
        method: GET
    steps:
      - name: fetch-orders
        type: step.db_query
        config:
          database: main-db
          query: "SELECT * FROM orders"
      - name: respond
        type: step.json_response
        config:
          status: 200

  delete-order:
    trigger:
      type: http
      config:
        path: /api/orders/{id}
        method: DELETE
    steps:
      - name: delete-order
        type: step.delegate
        config:
          service: order-service
