package cigen

import (
	"fmt"
	"sort"
	"strings"
)

// RenderJenkins generates a declarative Jenkinsfile from a CIPlan.
// It returns a map with a single key "Jenkinsfile".
//
// The output mirrors the GitHub Actions renderer's job set — plan / per-phase
// apply (scoped secrets + plan-guard + last-phase migrations) / smoke — mapped
// onto a single linear declarative `stages {}` block. Plan stages gate on
// changeRequest() (PR branches); apply/smoke stages gate on the default branch,
// which is correct only in a Jenkins Multibranch Pipeline (surfaced via a header
// comment). It deliberately emits no docker-build/deploy stage (ADR 0044).
func RenderJenkins(p *CIPlan) (map[string]string, error) {
	if p == nil {
		return nil, fmt.Errorf("RenderJenkins: plan is nil")
	}
	content, err := renderJenkinsfile(p)
	if err != nil {
		return nil, err
	}
	return map[string]string{"Jenkinsfile": content}, nil
}

func renderJenkinsfile(p *CIPlan) (string, error) {
	branch := p.DefaultBranch
	if branch == "" {
		branch = "main"
	}
	version := p.WfctlVersion
	if version == "" {
		version = "latest"
	}

	var b strings.Builder

	// Header: Multibranch precondition + sorted required-credentials union so the
	// operator knows which Jenkins credentials to pre-create.
	b.WriteString("// Requires a Jenkins Multibranch Pipeline job (generated by wfctl ci generate).\n")
	b.WriteString("//   Plan stages gate on changeRequest() (PR branches); apply/smoke stages gate\n")
	b.WriteString("//   on the default branch. In a standard single-branch job, changeRequest() is\n")
	b.WriteString("//   always false and plan stages will not run.\n")
	if creds := jenkinsCredentialUnion(p); len(creds) > 0 {
		fmt.Fprintf(&b, "// Required Jenkins credentials: %s\n", strings.Join(creds, ", "))
	}

	b.WriteString("pipeline {\n")
	b.WriteString("  agent { label 'linux' }\n")
	b.WriteString("  environment {\n")
	b.WriteString("    GOBIN = \"${WORKSPACE}/bin\"\n")
	b.WriteString("    PATH = \"${WORKSPACE}/bin:${PATH}\"\n")
	fmt.Fprintf(&b, "    WFCTL_VERSION = %q\n", version)
	b.WriteString("  }\n")
	b.WriteString("  stages {\n")

	// Plan stages (one per phase), gated on changeRequest().
	for _, phase := range p.Phases {
		fmt.Fprintf(&b, "    stage('Plan %s') {\n", phase.Name)
		b.WriteString("      when { changeRequest() }\n")
		b.WriteString("      steps {\n")
		writeJenkinsSetup(&b, p, phase)
		fmt.Fprintf(&b, "        sh \"wfctl infra plan --config '%s' --format markdown\"\n", phase.ConfigPath)
		b.WriteString("      }\n")
		b.WriteString("    }\n")
	}

	// Apply stages (one per phase, in declarative order), gated on the default
	// branch. Per-stage environment {} gives the per-phase secret scope the GHA
	// renderer gets via per-job env:.
	for i, phase := range p.Phases {
		fmt.Fprintf(&b, "    stage('Apply %s') {\n", phase.Name)
		fmt.Fprintf(&b, "      when { branch '%s' }\n", branch)

		// Source the secret set by branching on phase.Scoped (NOT len): a scoped
		// phase uses its own subset; an unscoped phase falls back to the union.
		secrets := p.Secrets
		if phase.Scoped {
			secrets = phase.Secrets
		}
		if len(secrets) > 0 {
			b.WriteString("      environment {\n")
			for _, name := range sortedSecretNames(secrets) {
				fmt.Fprintf(&b, "        %s = credentials('%s')\n", name, name)
			}
			b.WriteString("      }\n")
		}

		b.WriteString("      steps {\n")
		writeJenkinsSetup(&b, p, phase)
		if p.PlanGuard {
			writeJenkinsPlanGuard(&b, phase.ConfigPath)
		}
		// Migrations run only in the last phase, via the shared `wfctl migrations
		// up` runner (never `wfctl ci run --phase migrate`).
		if i == len(p.Phases)-1 && p.Migrations != nil {
			fmt.Fprintf(&b, "        sh \"%s\"\n", migrationsUpCommand(phase.ConfigPath, p.Migrations.Env))
		}
		fmt.Fprintf(&b, "        sh \"wfctl infra apply --config '%s' --auto-approve\"\n", phase.ConfigPath)
		b.WriteString("      }\n")
		b.WriteString("    }\n")
	}

	// Smoke stage.
	if p.Smoke != nil {
		b.WriteString("    stage('Smoke') {\n")
		fmt.Fprintf(&b, "      when { branch '%s' }\n", branch)
		b.WriteString("      steps {\n")
		fmt.Fprintf(&b, "        sh \"curl --fail --max-time 30 '%s'\"\n", p.Smoke.URL)
		b.WriteString("      }\n")
		b.WriteString("    }\n")
	}

	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

// writeJenkinsSetup installs wfctl into the workspace bin (on PATH via the
// pipeline environment) and, when needed, installs plugins for the phase config.
func writeJenkinsSetup(b *strings.Builder, p *CIPlan, phase DeployPhase) {
	// Single-quoted so the shell (not Groovy) expands the exported WFCTL_VERSION.
	b.WriteString("        sh 'go install github.com/GoCodeAlone/workflow/cmd/wfctl@${WFCTL_VERSION}'\n")
	if p.PluginInstall {
		fmt.Fprintf(b, "        sh \"wfctl plugin install --config '%s'\"\n", phase.ConfigPath)
	}
}

// writeJenkinsPlanGuard refuses to apply when the plan includes a replace or
// destroy of a protected resource. The plan output stays in the build log (tee)
// and a destructive plan fails the stage (exit 1) — no `|| true`.
func writeJenkinsPlanGuard(b *strings.Builder, configPath string) {
	b.WriteString("        sh '''\n")
	fmt.Fprintf(b, "          wfctl infra plan --config '%s' | tee plan-guard.txt\n", configPath)
	b.WriteString("          if grep -Eq -- '^[[:space:]]*(- delete|-/\\+ replace)[[:space:]]' plan-guard.txt || \\\n")
	b.WriteString("             grep -Eq -- 'Plan: .*([1-9][0-9]* to replace|[1-9][0-9]* to destroy)' plan-guard.txt; then\n")
	b.WriteString("            echo \"Refusing apply: plan includes replace or destroy of a protected resource.\" >&2\n")
	b.WriteString("            exit 1\n")
	b.WriteString("          fi\n")
	b.WriteString("        '''\n")
}

// jenkinsCredentialUnion returns the sorted, de-duplicated set of secret names
// the rendered Jenkinsfile binds, across the plan-wide union and any scoped
// phases — used for the operator-facing `// Required Jenkins credentials:` header.
func jenkinsCredentialUnion(p *CIPlan) []string {
	seen := make(map[string]bool)
	var names []string
	add := func(refs []SecretRef) {
		for _, s := range refs {
			if !seen[s.Name] {
				seen[s.Name] = true
				names = append(names, s.Name)
			}
		}
	}
	add(p.Secrets)
	for _, ph := range p.Phases {
		if ph.Scoped {
			add(ph.Secrets)
		}
	}
	sort.Strings(names)
	return names
}

// sortedSecretNames returns the secret names sorted for deterministic output.
func sortedSecretNames(refs []SecretRef) []string {
	names := make([]string, 0, len(refs))
	for _, s := range refs {
		names = append(names, s.Name)
	}
	sort.Strings(names)
	return names
}
