// infra_admin.proto — typed contracts for the host-side infra.admin
// workflow module's HTTP surface. Sole serialization shape is
// protojson over HTTP. v1 is read-only — mutations remain in
// `wfctl infra apply/destroy/drift`.
//
// Design: docs/plans/2026-05-27-infra-admin-dynamic-design.md §Strict Proto Contracts
// Plan:   docs/plans/2026-05-27-infra-admin-dynamic.md (Task 4)
//
// Hard invariants:
//   - Every typed input carries AdminAuthzEvidence. Read endpoints
//     require evidence.authz_checked && evidence.authz_allowed.
//     Default-deny semantics.
//   - Free-form per-resource AppliedConfig / Outputs payloads cross
//     the wire as bytes <name>_json, JSON-encoded by the handler.
//     The handler owns the serialization shape; the proto carries
//     opaque bytes (same pattern as plugin/external/proto/iac.proto).
//   - error field uses tag 100 (uniform discriminator across outputs
//     so generic decoders can sniff for a non-empty error before
//     consuming the typed payload).
//   - The HTTP audit-tail endpoint (GET /api/infra-admin/audit) is
//     NOT exposed as a gRPC RPC — it streams ndjson of
//     AdminAuditEntry directly per design doc §Access logging. The
//     5 declared RPCs cover every typed read endpoint.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: iac/admin/proto/infra_admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminAuthzEvidence carries the host-side authz outcome to handler
// library functions. The handler MUST refuse to serve when
// authz_checked is false (caller bypassed admin auth middleware) or
// authz_allowed is false (caller was denied). Subject + granted
// permissions are recorded in the audit log alongside each request.
type AdminAuthzEvidence struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuthzChecked       bool                   `protobuf:"varint,1,opt,name=authz_checked,json=authzChecked,proto3" json:"authz_checked,omitempty"`
	AuthzAllowed       bool                   `protobuf:"varint,2,opt,name=authz_allowed,json=authzAllowed,proto3" json:"authz_allowed,omitempty"`
	Subject            string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	GrantedPermissions []string               `protobuf:"bytes,4,rep,name=granted_permissions,json=grantedPermissions,proto3" json:"granted_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminAuthzEvidence) Reset() {
	*x = AdminAuthzEvidence{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuthzEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuthzEvidence) ProtoMessage() {}

func (x *AdminAuthzEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuthzEvidence.ProtoReflect.Descriptor instead.
func (*AdminAuthzEvidence) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminAuthzEvidence) GetAuthzChecked() bool {
	if x != nil {
		return x.AuthzChecked
	}
	return false
}

func (x *AdminAuthzEvidence) GetAuthzAllowed() bool {
	if x != nil {
		return x.AuthzAllowed
	}
	return false
}

func (x *AdminAuthzEvidence) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AdminAuthzEvidence) GetGrantedPermissions() []string {
	if x != nil {
		return x.GrantedPermissions
	}
	return nil
}

// AdminResourceSummary is the table-row shape for the resources list
// page. provider_module is the host YAML `name:` of the iac.provider
// module that owns this resource; provider_type is the underlying
// cloud provider string (aws/digitalocean/etc) read from that
// module's config.provider field at module Init time.
type AdminResourceSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                           // "infra.vpc"
	ProviderModule string                 `protobuf:"bytes,3,opt,name=provider_module,json=providerModule,proto3" json:"provider_module,omitempty"` // host module name (the YAML `name:`)
	ProviderType   string                 `protobuf:"bytes,4,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`       // from the iac.provider module's config `provider:` field
	ProviderId     string                 `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAtUnix  int64                  `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Dependencies   []string               `protobuf:"bytes,8,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	AppContext     string                 `protobuf:"bytes,9,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminResourceSummary) Reset() {
	*x = AdminResourceSummary{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceSummary) ProtoMessage() {}

func (x *AdminResourceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceSummary.ProtoReflect.Descriptor instead.
func (*AdminResourceSummary) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminResourceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminResourceSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdminResourceSummary) GetProviderModule() string {
	if x != nil {
		return x.ProviderModule
	}
	return ""
}

func (x *AdminResourceSummary) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *AdminResourceSummary) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AdminResourceSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminResourceSummary) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *AdminResourceSummary) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *AdminResourceSummary) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

// AdminResourceDetail extends the summary with the full per-resource
// state payload. applied_config_json + outputs_json are JSON-encoded
// by the handler; sensitive_outputs_redacted lists output keys whose
// values were stripped from outputs_json before serialization (the
// raw key names are safe to surface; the values are not).
type AdminResourceDetail struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Summary                  *AdminResourceSummary  `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	AppliedConfigJson        []byte                 `protobuf:"bytes,2,opt,name=applied_config_json,json=appliedConfigJson,proto3" json:"applied_config_json,omitempty"`
	OutputsJson              []byte                 `protobuf:"bytes,3,opt,name=outputs_json,json=outputsJson,proto3" json:"outputs_json,omitempty"`
	ConfigHash               string                 `protobuf:"bytes,4,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	LastDriftCheckUnix       int64                  `protobuf:"varint,5,opt,name=last_drift_check_unix,json=lastDriftCheckUnix,proto3" json:"last_drift_check_unix,omitempty"`
	SensitiveOutputsRedacted []string               `protobuf:"bytes,6,rep,name=sensitive_outputs_redacted,json=sensitiveOutputsRedacted,proto3" json:"sensitive_outputs_redacted,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AdminResourceDetail) Reset() {
	*x = AdminResourceDetail{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceDetail) ProtoMessage() {}

func (x *AdminResourceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceDetail.ProtoReflect.Descriptor instead.
func (*AdminResourceDetail) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminResourceDetail) GetSummary() *AdminResourceSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *AdminResourceDetail) GetAppliedConfigJson() []byte {
	if x != nil {
		return x.AppliedConfigJson
	}
	return nil
}

func (x *AdminResourceDetail) GetOutputsJson() []byte {
	if x != nil {
		return x.OutputsJson
	}
	return nil
}

func (x *AdminResourceDetail) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *AdminResourceDetail) GetLastDriftCheckUnix() int64 {
	if x != nil {
		return x.LastDriftCheckUnix
	}
	return 0
}

func (x *AdminResourceDetail) GetSensitiveOutputsRedacted() []string {
	if x != nil {
		return x.SensitiveOutputsRedacted
	}
	return nil
}

// AdminListResourcesInput is the request shape for the ListResources
// RPC. Filters narrow the returned set; evidence carries the host-side
// authz outcome (default-deny semantics).
type AdminListResourcesInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TypeFilter       string                 `protobuf:"bytes,1,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	ProviderFilter   string                 `protobuf:"bytes,2,opt,name=provider_filter,json=providerFilter,proto3" json:"provider_filter,omitempty"`
	AppContextFilter string                 `protobuf:"bytes,3,opt,name=app_context_filter,json=appContextFilter,proto3" json:"app_context_filter,omitempty"`
	EnvName          string                 `protobuf:"bytes,4,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	Evidence         *AdminAuthzEvidence    `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminListResourcesInput) Reset() {
	*x = AdminListResourcesInput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListResourcesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListResourcesInput) ProtoMessage() {}

func (x *AdminListResourcesInput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListResourcesInput.ProtoReflect.Descriptor instead.
func (*AdminListResourcesInput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminListResourcesInput) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *AdminListResourcesInput) GetProviderFilter() string {
	if x != nil {
		return x.ProviderFilter
	}
	return ""
}

func (x *AdminListResourcesInput) GetAppContextFilter() string {
	if x != nil {
		return x.AppContextFilter
	}
	return ""
}

func (x *AdminListResourcesInput) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *AdminListResourcesInput) GetEvidence() *AdminAuthzEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// AdminListResourcesOutput is the response shape for the ListResources
// RPC. error is set when the handler refused (e.g. authz denied); when
// non-empty, consumers MUST ignore the typed payload.
type AdminListResourcesOutput struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Resources     []*AdminResourceSummary `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Error         string                  `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListResourcesOutput) Reset() {
	*x = AdminListResourcesOutput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListResourcesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListResourcesOutput) ProtoMessage() {}

func (x *AdminListResourcesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListResourcesOutput.ProtoReflect.Descriptor instead.
func (*AdminListResourcesOutput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminListResourcesOutput) GetResources() []*AdminResourceSummary {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AdminListResourcesOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AdminGetResourceInput is the request shape for the GetResource RPC.
// name is the resource's host-side identity (the YAML `name:`); the
// returned detail includes the full applied config + outputs.
type AdminGetResourceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnvName       string                 `protobuf:"bytes,2,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	Evidence      *AdminAuthzEvidence    `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetResourceInput) Reset() {
	*x = AdminGetResourceInput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetResourceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetResourceInput) ProtoMessage() {}

func (x *AdminGetResourceInput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetResourceInput.ProtoReflect.Descriptor instead.
func (*AdminGetResourceInput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminGetResourceInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminGetResourceInput) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *AdminGetResourceInput) GetEvidence() *AdminAuthzEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// AdminGetResourceOutput is the response shape for the GetResource RPC.
// Carries AdminResourceDetail when found; error when the resource is
// missing or authz denied.
type AdminGetResourceOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *AdminResourceDetail   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetResourceOutput) Reset() {
	*x = AdminGetResourceOutput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetResourceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetResourceOutput) ProtoMessage() {}

func (x *AdminGetResourceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetResourceOutput.ProtoReflect.Descriptor instead.
func (*AdminGetResourceOutput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminGetResourceOutput) GetResource() *AdminResourceDetail {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AdminGetResourceOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AdminFieldSpec describes one field of a typed infra.* Config so the
// new-resource form-builder can render the right input control.
//   - kind: one of {enum, enum_dynamic, string, number, bool,
//     array_string, array_object, object} — see catalog/fields.go.
//   - enum_source (only for kind == enum_dynamic): "providers" |
//     "regions" | "sizes" | "engines" — the form fetches dynamic
//     options at render time.
//   - depends_on_field: when set, this field's options are filtered
//     by the value the user picked for depends_on_field (e.g. region
//     options depend on provider).
//   - element_kind: only meaningful for array_* kinds.
//   - sensitive: when true, the form renders a masked input AND the
//     value is excluded from any rendered preview.
type AdminFieldSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label          string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Required       bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	EnumValues     []string               `protobuf:"bytes,5,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	EnumSource     string                 `protobuf:"bytes,6,opt,name=enum_source,json=enumSource,proto3" json:"enum_source,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue   string                 `protobuf:"bytes,8,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Sensitive      bool                   `protobuf:"varint,9,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	ElementKind    string                 `protobuf:"bytes,10,opt,name=element_kind,json=elementKind,proto3" json:"element_kind,omitempty"`
	MinCount       int32                  `protobuf:"varint,11,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	MaxCount       int32                  `protobuf:"varint,12,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	DependsOnField string                 `protobuf:"bytes,13,opt,name=depends_on_field,json=dependsOnField,proto3" json:"depends_on_field,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminFieldSpec) Reset() {
	*x = AdminFieldSpec{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFieldSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFieldSpec) ProtoMessage() {}

func (x *AdminFieldSpec) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFieldSpec.ProtoReflect.Descriptor instead.
func (*AdminFieldSpec) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminFieldSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminFieldSpec) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminFieldSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdminFieldSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AdminFieldSpec) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *AdminFieldSpec) GetEnumSource() string {
	if x != nil {
		return x.EnumSource
	}
	return ""
}

func (x *AdminFieldSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminFieldSpec) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *AdminFieldSpec) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *AdminFieldSpec) GetElementKind() string {
	if x != nil {
		return x.ElementKind
	}
	return ""
}

func (x *AdminFieldSpec) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

func (x *AdminFieldSpec) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *AdminFieldSpec) GetDependsOnField() string {
	if x != nil {
		return x.DependsOnField
	}
	return ""
}

// AdminResourceTypeMetadata is the form-builder's view of one
// infra.* Config message. config_message_fqn is the fully-qualified
// proto message name in workflow-plugin-infra/internal/contracts/
// infra.proto (e.g. "workflow.plugin.infra.v1.VPCConfig") so callers
// can correlate against the vendored proto descriptor.
type AdminResourceTypeMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ConfigMessageFqn   string                 `protobuf:"bytes,2,opt,name=config_message_fqn,json=configMessageFqn,proto3" json:"config_message_fqn,omitempty"`
	Fields             []*AdminFieldSpec      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	SupportedProviders []string               `protobuf:"bytes,4,rep,name=supported_providers,json=supportedProviders,proto3" json:"supported_providers,omitempty"`
	Description        string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminResourceTypeMetadata) Reset() {
	*x = AdminResourceTypeMetadata{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceTypeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceTypeMetadata) ProtoMessage() {}

func (x *AdminResourceTypeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceTypeMetadata.ProtoReflect.Descriptor instead.
func (*AdminResourceTypeMetadata) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminResourceTypeMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdminResourceTypeMetadata) GetConfigMessageFqn() string {
	if x != nil {
		return x.ConfigMessageFqn
	}
	return ""
}

func (x *AdminResourceTypeMetadata) GetFields() []*AdminFieldSpec {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminResourceTypeMetadata) GetSupportedProviders() []string {
	if x != nil {
		return x.SupportedProviders
	}
	return nil
}

func (x *AdminResourceTypeMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// AdminListResourceTypesInput is the request shape for the
// ListResourceTypes RPC. provider_filter narrows the returned types to
// those a given provider supports.
type AdminListResourceTypesInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderFilter string                 `protobuf:"bytes,1,opt,name=provider_filter,json=providerFilter,proto3" json:"provider_filter,omitempty"`
	Evidence       *AdminAuthzEvidence    `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminListResourceTypesInput) Reset() {
	*x = AdminListResourceTypesInput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListResourceTypesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListResourceTypesInput) ProtoMessage() {}

func (x *AdminListResourceTypesInput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListResourceTypesInput.ProtoReflect.Descriptor instead.
func (*AdminListResourceTypesInput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminListResourceTypesInput) GetProviderFilter() string {
	if x != nil {
		return x.ProviderFilter
	}
	return ""
}

func (x *AdminListResourceTypesInput) GetEvidence() *AdminAuthzEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// AdminListResourceTypesOutput is the response shape for the
// ListResourceTypes RPC. types is the form-builder's view of every
// registered infra.* Config (one entry per FieldSpecCatalog type).
type AdminListResourceTypesOutput struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Types         []*AdminResourceTypeMetadata `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Error         string                       `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListResourceTypesOutput) Reset() {
	*x = AdminListResourceTypesOutput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListResourceTypesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListResourceTypesOutput) ProtoMessage() {}

func (x *AdminListResourceTypesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListResourceTypesOutput.ProtoReflect.Descriptor instead.
func (*AdminListResourceTypesOutput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminListResourceTypesOutput) GetTypes() []*AdminResourceTypeMetadata {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *AdminListResourceTypesOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AdminProviderSummary is the ListProviders response row. v1
// populates supported_regions / supported_types / supported_engines
// from the host-side catalog (regions.go + engines.go + fields.go);
// regions_source is the literal string "local-catalog" so consumers
// can distinguish v1's local lookup from a future v1.1
// IaCProviderRegionLister gRPC service.
type AdminProviderSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModuleName       string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ProviderType     string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	Capabilities     []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SupportedRegions []string               `protobuf:"bytes,4,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	SupportedTypes   []string               `protobuf:"bytes,5,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	SupportedEngines []string               `protobuf:"bytes,6,rep,name=supported_engines,json=supportedEngines,proto3" json:"supported_engines,omitempty"`
	RegionsSource    string                 `protobuf:"bytes,7,opt,name=regions_source,json=regionsSource,proto3" json:"regions_source,omitempty"` // "local-catalog" for v1
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminProviderSummary) Reset() {
	*x = AdminProviderSummary{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProviderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProviderSummary) ProtoMessage() {}

func (x *AdminProviderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProviderSummary.ProtoReflect.Descriptor instead.
func (*AdminProviderSummary) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminProviderSummary) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *AdminProviderSummary) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *AdminProviderSummary) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AdminProviderSummary) GetSupportedRegions() []string {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

func (x *AdminProviderSummary) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *AdminProviderSummary) GetSupportedEngines() []string {
	if x != nil {
		return x.SupportedEngines
	}
	return nil
}

func (x *AdminProviderSummary) GetRegionsSource() string {
	if x != nil {
		return x.RegionsSource
	}
	return ""
}

// AdminListProvidersInput is the request shape for the ListProviders
// RPC. env_name selects the per-environment overlay.
type AdminListProvidersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvName       string                 `protobuf:"bytes,1,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	Evidence      *AdminAuthzEvidence    `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListProvidersInput) Reset() {
	*x = AdminListProvidersInput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListProvidersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListProvidersInput) ProtoMessage() {}

func (x *AdminListProvidersInput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListProvidersInput.ProtoReflect.Descriptor instead.
func (*AdminListProvidersInput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminListProvidersInput) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *AdminListProvidersInput) GetEvidence() *AdminAuthzEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// AdminListProvidersOutput is the response shape for the ListProviders
// RPC. One AdminProviderSummary per iac.provider module declared in the
// host's WorkflowConfig.
type AdminListProvidersOutput struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Providers     []*AdminProviderSummary `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	Error         string                  `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListProvidersOutput) Reset() {
	*x = AdminListProvidersOutput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListProvidersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListProvidersOutput) ProtoMessage() {}

func (x *AdminListProvidersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListProvidersOutput.ProtoReflect.Descriptor instead.
func (*AdminListProvidersOutput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminListProvidersOutput) GetProviders() []*AdminProviderSummary {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *AdminListProvidersOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AdminGenerateConfigInput carries the form-builder submission.
// field_values is keyed by AdminFieldSpec.name; values are always
// string-encoded (the catalog's kind metadata is the authority for
// coercion to proto types). resource_name is the host YAML `name:`
// the user picked; provider_module references one of the
// AdminProviderSummary.module_name values returned by ListProviders.
type AdminGenerateConfigInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceType   string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceName   string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ProviderModule string                 `protobuf:"bytes,3,opt,name=provider_module,json=providerModule,proto3" json:"provider_module,omitempty"`
	FieldValues    map[string]string      `protobuf:"bytes,4,rep,name=field_values,json=fieldValues,proto3" json:"field_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Evidence       *AdminAuthzEvidence    `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminGenerateConfigInput) Reset() {
	*x = AdminGenerateConfigInput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGenerateConfigInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGenerateConfigInput) ProtoMessage() {}

func (x *AdminGenerateConfigInput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGenerateConfigInput.ProtoReflect.Descriptor instead.
func (*AdminGenerateConfigInput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminGenerateConfigInput) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AdminGenerateConfigInput) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AdminGenerateConfigInput) GetProviderModule() string {
	if x != nil {
		return x.ProviderModule
	}
	return ""
}

func (x *AdminGenerateConfigInput) GetFieldValues() map[string]string {
	if x != nil {
		return x.FieldValues
	}
	return nil
}

func (x *AdminGenerateConfigInput) GetEvidence() *AdminAuthzEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// AdminGenerateConfigOutput is the response shape for the
// GenerateConfig RPC. yaml_snippet is the typed-coerced YAML the form
// produced; validation_errors carries any per-field validation
// failures the catalog reported (form remains submittable on
// validation_errors — `error` is reserved for handler-level failures
// like authz denial).
type AdminGenerateConfigOutput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	YamlSnippet      string                 `protobuf:"bytes,1,opt,name=yaml_snippet,json=yamlSnippet,proto3" json:"yaml_snippet,omitempty"`
	ValidationErrors []string               `protobuf:"bytes,2,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	Error            string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminGenerateConfigOutput) Reset() {
	*x = AdminGenerateConfigOutput{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGenerateConfigOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGenerateConfigOutput) ProtoMessage() {}

func (x *AdminGenerateConfigOutput) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGenerateConfigOutput.ProtoReflect.Descriptor instead.
func (*AdminGenerateConfigOutput) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminGenerateConfigOutput) GetYamlSnippet() string {
	if x != nil {
		return x.YamlSnippet
	}
	return ""
}

func (x *AdminGenerateConfigOutput) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *AdminGenerateConfigOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AdminAuditEntry is the line shape for the audit log (one entry per
// non-noop admin action) AND the streaming response shape of the
// HTTP audit-tail endpoint (GET /api/infra-admin/audit). schema_version
// starts at 1; bumps are additive (new fields) until a breaking
// change forces a major.
type AdminAuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Targets       []string               `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	AppContext    string                 `protobuf:"bytes,7,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuditEntry) Reset() {
	*x = AdminAuditEntry{}
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuditEntry) ProtoMessage() {}

func (x *AdminAuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_iac_admin_proto_infra_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuditEntry.ProtoReflect.Descriptor instead.
func (*AdminAuditEntry) Descriptor() ([]byte, []int) {
	return file_iac_admin_proto_infra_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AdminAuditEntry) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AdminAuditEntry) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *AdminAuditEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AdminAuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AdminAuditEntry) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AdminAuditEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AdminAuditEntry) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

var File_iac_admin_proto_infra_admin_proto protoreflect.FileDescriptor

const file_iac_admin_proto_infra_admin_proto_rawDesc = "" +
	"\n" +
	"!iac/admin/proto/infra_admin.proto\x12\x0fworkflow.iac.v1\"\xa9\x01\n" +
	"\x12AdminAuthzEvidence\x12#\n" +
	"\rauthz_checked\x18\x01 \x01(\bR\fauthzChecked\x12#\n" +
	"\rauthz_allowed\x18\x02 \x01(\bR\fauthzAllowed\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12/\n" +
	"\x13granted_permissions\x18\x04 \x03(\tR\x12grantedPermissions\"\xb2\x02\n" +
	"\x14AdminResourceSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12'\n" +
	"\x0fprovider_module\x18\x03 \x01(\tR\x0eproviderModule\x12#\n" +
	"\rprovider_type\x18\x04 \x01(\tR\fproviderType\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\x12\"\n" +
	"\fdependencies\x18\b \x03(\tR\fdependencies\x12\x1f\n" +
	"\vapp_context\x18\t \x01(\tR\n" +
	"appContext\"\xbb\x02\n" +
	"\x13AdminResourceDetail\x12?\n" +
	"\asummary\x18\x01 \x01(\v2%.workflow.iac.v1.AdminResourceSummaryR\asummary\x12.\n" +
	"\x13applied_config_json\x18\x02 \x01(\fR\x11appliedConfigJson\x12!\n" +
	"\foutputs_json\x18\x03 \x01(\fR\voutputsJson\x12\x1f\n" +
	"\vconfig_hash\x18\x04 \x01(\tR\n" +
	"configHash\x121\n" +
	"\x15last_drift_check_unix\x18\x05 \x01(\x03R\x12lastDriftCheckUnix\x12<\n" +
	"\x1asensitive_outputs_redacted\x18\x06 \x03(\tR\x18sensitiveOutputsRedacted\"\xfa\x01\n" +
	"\x17AdminListResourcesInput\x12\x1f\n" +
	"\vtype_filter\x18\x01 \x01(\tR\n" +
	"typeFilter\x12'\n" +
	"\x0fprovider_filter\x18\x02 \x01(\tR\x0eproviderFilter\x12,\n" +
	"\x12app_context_filter\x18\x03 \x01(\tR\x10appContextFilter\x12\x19\n" +
	"\benv_name\x18\x04 \x01(\tR\aenvName\x12?\n" +
	"\bevidence\x18\x05 \x01(\v2#.workflow.iac.v1.AdminAuthzEvidenceR\bevidenceJ\x04\b\x06\x10dJ\x05\be\x10\xc8\x01\"\x82\x01\n" +
	"\x18AdminListResourcesOutput\x12C\n" +
	"\tresources\x18\x01 \x03(\v2%.workflow.iac.v1.AdminResourceSummaryR\tresources\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorJ\x04\b\x02\x10dJ\x05\be\x10\xc8\x01\"\x94\x01\n" +
	"\x15AdminGetResourceInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\benv_name\x18\x02 \x01(\tR\aenvName\x12?\n" +
	"\bevidence\x18\x03 \x01(\v2#.workflow.iac.v1.AdminAuthzEvidenceR\bevidenceJ\x04\b\x04\x10dJ\x05\be\x10\xc8\x01\"}\n" +
	"\x16AdminGetResourceOutput\x12@\n" +
	"\bresource\x18\x01 \x01(\v2$.workflow.iac.v1.AdminResourceDetailR\bresource\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorJ\x04\b\x02\x10dJ\x05\be\x10\xc8\x01\"\x98\x03\n" +
	"\x0eAdminFieldSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1f\n" +
	"\venum_values\x18\x05 \x03(\tR\n" +
	"enumValues\x12\x1f\n" +
	"\venum_source\x18\x06 \x01(\tR\n" +
	"enumSource\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12#\n" +
	"\rdefault_value\x18\b \x01(\tR\fdefaultValue\x12\x1c\n" +
	"\tsensitive\x18\t \x01(\bR\tsensitive\x12!\n" +
	"\felement_kind\x18\n" +
	" \x01(\tR\velementKind\x12\x1b\n" +
	"\tmin_count\x18\v \x01(\x05R\bminCount\x12\x1b\n" +
	"\tmax_count\x18\f \x01(\x05R\bmaxCount\x12(\n" +
	"\x10depends_on_field\x18\r \x01(\tR\x0edependsOnField\"\xe9\x01\n" +
	"\x19AdminResourceTypeMetadata\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12,\n" +
	"\x12config_message_fqn\x18\x02 \x01(\tR\x10configMessageFqn\x127\n" +
	"\x06fields\x18\x03 \x03(\v2\x1f.workflow.iac.v1.AdminFieldSpecR\x06fields\x12/\n" +
	"\x13supported_providers\x18\x04 \x03(\tR\x12supportedProviders\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x94\x01\n" +
	"\x1bAdminListResourceTypesInput\x12'\n" +
	"\x0fprovider_filter\x18\x01 \x01(\tR\x0eproviderFilter\x12?\n" +
	"\bevidence\x18\x02 \x01(\v2#.workflow.iac.v1.AdminAuthzEvidenceR\bevidenceJ\x04\b\x03\x10dJ\x05\be\x10\xc8\x01\"\x83\x01\n" +
	"\x1cAdminListResourceTypesOutput\x12@\n" +
	"\x05types\x18\x01 \x03(\v2*.workflow.iac.v1.AdminResourceTypeMetadataR\x05types\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorJ\x04\b\x02\x10dJ\x05\be\x10\xc8\x01\"\xaa\x02\n" +
	"\x14AdminProviderSummary\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12+\n" +
	"\x11supported_regions\x18\x04 \x03(\tR\x10supportedRegions\x12'\n" +
	"\x0fsupported_types\x18\x05 \x03(\tR\x0esupportedTypes\x12+\n" +
	"\x11supported_engines\x18\x06 \x03(\tR\x10supportedEngines\x12%\n" +
	"\x0eregions_source\x18\a \x01(\tR\rregionsSource\"\x82\x01\n" +
	"\x17AdminListProvidersInput\x12\x19\n" +
	"\benv_name\x18\x01 \x01(\tR\aenvName\x12?\n" +
	"\bevidence\x18\x02 \x01(\v2#.workflow.iac.v1.AdminAuthzEvidenceR\bevidenceJ\x04\b\x03\x10dJ\x05\be\x10\xc8\x01\"\x82\x01\n" +
	"\x18AdminListProvidersOutput\x12C\n" +
	"\tproviders\x18\x01 \x03(\v2%.workflow.iac.v1.AdminProviderSummaryR\tproviders\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorJ\x04\b\x02\x10dJ\x05\be\x10\xc8\x01\"\xfa\x02\n" +
	"\x18AdminGenerateConfigInput\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12'\n" +
	"\x0fprovider_module\x18\x03 \x01(\tR\x0eproviderModule\x12]\n" +
	"\ffield_values\x18\x04 \x03(\v2:.workflow.iac.v1.AdminGenerateConfigInput.FieldValuesEntryR\vfieldValues\x12?\n" +
	"\bevidence\x18\x05 \x01(\v2#.workflow.iac.v1.AdminAuthzEvidenceR\bevidence\x1a>\n" +
	"\x10FieldValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x06\x10dJ\x05\be\x10\xc8\x01\"\x8e\x01\n" +
	"\x19AdminGenerateConfigOutput\x12!\n" +
	"\fyaml_snippet\x18\x01 \x01(\tR\vyamlSnippet\x12+\n" +
	"\x11validation_errors\x18\x02 \x03(\tR\x10validationErrors\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorJ\x04\b\x03\x10dJ\x05\be\x10\xc8\x01\"\xd6\x01\n" +
	"\x0fAdminAuditEntry\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x18\n" +
	"\atargets\x18\x05 \x03(\tR\atargets\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x1f\n" +
	"\vapp_context\x18\a \x01(\tR\n" +
	"appContext2\x9a\x04\n" +
	"\x11InfraAdminService\x12d\n" +
	"\rListResources\x12(.workflow.iac.v1.AdminListResourcesInput\x1a).workflow.iac.v1.AdminListResourcesOutput\x12^\n" +
	"\vGetResource\x12&.workflow.iac.v1.AdminGetResourceInput\x1a'.workflow.iac.v1.AdminGetResourceOutput\x12p\n" +
	"\x11ListResourceTypes\x12,.workflow.iac.v1.AdminListResourceTypesInput\x1a-.workflow.iac.v1.AdminListResourceTypesOutput\x12d\n" +
	"\rListProviders\x12(.workflow.iac.v1.AdminListProvidersInput\x1a).workflow.iac.v1.AdminListProvidersOutput\x12g\n" +
	"\x0eGenerateConfig\x12).workflow.iac.v1.AdminGenerateConfigInput\x1a*.workflow.iac.v1.AdminGenerateConfigOutputB9Z7github.com/GoCodeAlone/workflow/iac/admin/proto;adminpbb\x06proto3"

var (
	file_iac_admin_proto_infra_admin_proto_rawDescOnce sync.Once
	file_iac_admin_proto_infra_admin_proto_rawDescData []byte
)

func file_iac_admin_proto_infra_admin_proto_rawDescGZIP() []byte {
	file_iac_admin_proto_infra_admin_proto_rawDescOnce.Do(func() {
		file_iac_admin_proto_infra_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iac_admin_proto_infra_admin_proto_rawDesc), len(file_iac_admin_proto_infra_admin_proto_rawDesc)))
	})
	return file_iac_admin_proto_infra_admin_proto_rawDescData
}

var file_iac_admin_proto_infra_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_iac_admin_proto_infra_admin_proto_goTypes = []any{
	(*AdminAuthzEvidence)(nil),           // 0: workflow.iac.v1.AdminAuthzEvidence
	(*AdminResourceSummary)(nil),         // 1: workflow.iac.v1.AdminResourceSummary
	(*AdminResourceDetail)(nil),          // 2: workflow.iac.v1.AdminResourceDetail
	(*AdminListResourcesInput)(nil),      // 3: workflow.iac.v1.AdminListResourcesInput
	(*AdminListResourcesOutput)(nil),     // 4: workflow.iac.v1.AdminListResourcesOutput
	(*AdminGetResourceInput)(nil),        // 5: workflow.iac.v1.AdminGetResourceInput
	(*AdminGetResourceOutput)(nil),       // 6: workflow.iac.v1.AdminGetResourceOutput
	(*AdminFieldSpec)(nil),               // 7: workflow.iac.v1.AdminFieldSpec
	(*AdminResourceTypeMetadata)(nil),    // 8: workflow.iac.v1.AdminResourceTypeMetadata
	(*AdminListResourceTypesInput)(nil),  // 9: workflow.iac.v1.AdminListResourceTypesInput
	(*AdminListResourceTypesOutput)(nil), // 10: workflow.iac.v1.AdminListResourceTypesOutput
	(*AdminProviderSummary)(nil),         // 11: workflow.iac.v1.AdminProviderSummary
	(*AdminListProvidersInput)(nil),      // 12: workflow.iac.v1.AdminListProvidersInput
	(*AdminListProvidersOutput)(nil),     // 13: workflow.iac.v1.AdminListProvidersOutput
	(*AdminGenerateConfigInput)(nil),     // 14: workflow.iac.v1.AdminGenerateConfigInput
	(*AdminGenerateConfigOutput)(nil),    // 15: workflow.iac.v1.AdminGenerateConfigOutput
	(*AdminAuditEntry)(nil),              // 16: workflow.iac.v1.AdminAuditEntry
	nil,                                  // 17: workflow.iac.v1.AdminGenerateConfigInput.FieldValuesEntry
}
var file_iac_admin_proto_infra_admin_proto_depIdxs = []int32{
	1,  // 0: workflow.iac.v1.AdminResourceDetail.summary:type_name -> workflow.iac.v1.AdminResourceSummary
	0,  // 1: workflow.iac.v1.AdminListResourcesInput.evidence:type_name -> workflow.iac.v1.AdminAuthzEvidence
	1,  // 2: workflow.iac.v1.AdminListResourcesOutput.resources:type_name -> workflow.iac.v1.AdminResourceSummary
	0,  // 3: workflow.iac.v1.AdminGetResourceInput.evidence:type_name -> workflow.iac.v1.AdminAuthzEvidence
	2,  // 4: workflow.iac.v1.AdminGetResourceOutput.resource:type_name -> workflow.iac.v1.AdminResourceDetail
	7,  // 5: workflow.iac.v1.AdminResourceTypeMetadata.fields:type_name -> workflow.iac.v1.AdminFieldSpec
	0,  // 6: workflow.iac.v1.AdminListResourceTypesInput.evidence:type_name -> workflow.iac.v1.AdminAuthzEvidence
	8,  // 7: workflow.iac.v1.AdminListResourceTypesOutput.types:type_name -> workflow.iac.v1.AdminResourceTypeMetadata
	0,  // 8: workflow.iac.v1.AdminListProvidersInput.evidence:type_name -> workflow.iac.v1.AdminAuthzEvidence
	11, // 9: workflow.iac.v1.AdminListProvidersOutput.providers:type_name -> workflow.iac.v1.AdminProviderSummary
	17, // 10: workflow.iac.v1.AdminGenerateConfigInput.field_values:type_name -> workflow.iac.v1.AdminGenerateConfigInput.FieldValuesEntry
	0,  // 11: workflow.iac.v1.AdminGenerateConfigInput.evidence:type_name -> workflow.iac.v1.AdminAuthzEvidence
	3,  // 12: workflow.iac.v1.InfraAdminService.ListResources:input_type -> workflow.iac.v1.AdminListResourcesInput
	5,  // 13: workflow.iac.v1.InfraAdminService.GetResource:input_type -> workflow.iac.v1.AdminGetResourceInput
	9,  // 14: workflow.iac.v1.InfraAdminService.ListResourceTypes:input_type -> workflow.iac.v1.AdminListResourceTypesInput
	12, // 15: workflow.iac.v1.InfraAdminService.ListProviders:input_type -> workflow.iac.v1.AdminListProvidersInput
	14, // 16: workflow.iac.v1.InfraAdminService.GenerateConfig:input_type -> workflow.iac.v1.AdminGenerateConfigInput
	4,  // 17: workflow.iac.v1.InfraAdminService.ListResources:output_type -> workflow.iac.v1.AdminListResourcesOutput
	6,  // 18: workflow.iac.v1.InfraAdminService.GetResource:output_type -> workflow.iac.v1.AdminGetResourceOutput
	10, // 19: workflow.iac.v1.InfraAdminService.ListResourceTypes:output_type -> workflow.iac.v1.AdminListResourceTypesOutput
	13, // 20: workflow.iac.v1.InfraAdminService.ListProviders:output_type -> workflow.iac.v1.AdminListProvidersOutput
	15, // 21: workflow.iac.v1.InfraAdminService.GenerateConfig:output_type -> workflow.iac.v1.AdminGenerateConfigOutput
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_iac_admin_proto_infra_admin_proto_init() }
func file_iac_admin_proto_infra_admin_proto_init() {
	if File_iac_admin_proto_infra_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iac_admin_proto_infra_admin_proto_rawDesc), len(file_iac_admin_proto_infra_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iac_admin_proto_infra_admin_proto_goTypes,
		DependencyIndexes: file_iac_admin_proto_infra_admin_proto_depIdxs,
		MessageInfos:      file_iac_admin_proto_infra_admin_proto_msgTypes,
	}.Build()
	File_iac_admin_proto_infra_admin_proto = out.File
	file_iac_admin_proto_infra_admin_proto_goTypes = nil
	file_iac_admin_proto_infra_admin_proto_depIdxs = nil
}
