package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/GoCodeAlone/workflow/config"
	"gopkg.in/yaml.v3"
)

func runCIInit(args []string) error {
	fs := flag.NewFlagSet("ci init", flag.ContinueOnError)
	platform := fs.String("platform", "github-actions", "CI platform: github-actions, gitlab-ci")
	configFile := fs.String("config", "app.yaml", "Workflow config file")
	output := fs.String("output", "", "Output file path (default: .github/workflows/ci.yml or .gitlab-ci.yml)")
	fs.Usage = func() {
		fmt.Fprintf(fs.Output(), `Usage: wfctl ci init [options]

Generate a bootstrap CI YAML file for the specified CI platform.
The generated file calls wfctl ci run to execute build/test phases.

Options:
`)
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}

	// Read config to detect environments.
	var cfg config.WorkflowConfig
	if data, err := os.ReadFile(*configFile); err == nil {
		_ = yaml.Unmarshal(data, &cfg)
	}

	var content, defaultOutput string
	switch *platform {
	case "github-actions":
		content = generateGHABootstrap(&cfg)
		defaultOutput = ".github/workflows/ci.yml"
	case "gitlab-ci":
		content = generateGitLabCIBootstrap(&cfg)
		defaultOutput = ".gitlab-ci.yml"
	default:
		return fmt.Errorf("unsupported platform %q (supported: github-actions, gitlab-ci)", *platform)
	}

	outPath := *output
	if outPath == "" {
		outPath = defaultOutput
	}

	// Create parent directories if needed.
	if dir := dirOf(outPath); dir != "" {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return fmt.Errorf("create dir %s: %w", dir, err)
		}
	}

	if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("wrote %s\n", outPath)
	return nil
}

// dirOf returns the directory part of a path, or empty string if path has no dir.
func dirOf(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' || path[i] == '\\' {
			return path[:i]
		}
	}
	return ""
}

func generateGHABootstrap(cfg *config.WorkflowConfig) string {
	var sb strings.Builder
	sb.WriteString("# Generated by wfctl ci init -- customize as needed\n")
	sb.WriteString("name: CI/CD\n")
	sb.WriteString("on:\n")
	sb.WriteString("  push:\n")
	sb.WriteString("    branches: [main]\n")
	sb.WriteString("  pull_request:\n")
	sb.WriteString("jobs:\n")
	sb.WriteString("  build-test:\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
	sb.WriteString("      - run: wfctl ci run --phase build,test\n")

	// Emit one deploy job per environment in ci.deploy.environments.
	if cfg != nil && cfg.CI != nil && cfg.CI.Deploy != nil {
		for envName, env := range cfg.CI.Deploy.Environments {
			if env == nil {
				continue
			}
			jobName := "deploy-" + strings.ReplaceAll(envName, ".", "-")
			sb.WriteString("  " + jobName + ":\n")
			sb.WriteString("    runs-on: ubuntu-latest\n")
			sb.WriteString("    needs: [build-test]\n")
			if env.RequireApproval {
				sb.WriteString("    environment: " + envName + "\n")
			}
			sb.WriteString("    steps:\n")
			sb.WriteString("      - uses: actions/checkout@v4\n")
			sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
			sb.WriteString("      - run: wfctl ci run --phase deploy --env " + envName + "\n")
		}
	}

	return sb.String()
}

func generateGitLabCIBootstrap(cfg *config.WorkflowConfig) string {
	var sb strings.Builder
	sb.WriteString("# Generated by wfctl ci init -- customize as needed\n")
	sb.WriteString("stages:\n")
	sb.WriteString("  - build\n")
	sb.WriteString("  - test\n")

	// Add deploy stages for each environment.
	if cfg != nil && cfg.CI != nil && cfg.CI.Deploy != nil {
		for envName := range cfg.CI.Deploy.Environments {
			sb.WriteString("  - deploy-" + strings.ReplaceAll(envName, ".", "-") + "\n")
		}
	}

	sb.WriteString("\nbuild:\n")
	sb.WriteString("  stage: build\n")
	sb.WriteString("  script:\n")
	sb.WriteString("    - wfctl ci run --phase build\n")
	sb.WriteString("  rules:\n")
	sb.WriteString("    - if: $CI_COMMIT_BRANCH == \"main\"\n")
	sb.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")

	sb.WriteString("\ntest:\n")
	sb.WriteString("  stage: test\n")
	sb.WriteString("  needs: [build]\n")
	sb.WriteString("  script:\n")
	sb.WriteString("    - wfctl ci run --phase test\n")
	sb.WriteString("  rules:\n")
	sb.WriteString("    - if: $CI_COMMIT_BRANCH == \"main\"\n")
	sb.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")

	// Emit deploy jobs.
	if cfg != nil && cfg.CI != nil && cfg.CI.Deploy != nil {
		for envName, env := range cfg.CI.Deploy.Environments {
			if env == nil {
				continue
			}
			stageID := strings.ReplaceAll(envName, ".", "-")
			sb.WriteString("\ndeploy-" + stageID + ":\n")
			sb.WriteString("  stage: deploy-" + stageID + "\n")
			sb.WriteString("  needs: [test]\n")
			sb.WriteString("  script:\n")
			sb.WriteString("    - wfctl ci run --phase deploy --env " + envName + "\n")
			if env.RequireApproval {
				sb.WriteString("  when: manual\n")
			}
			sb.WriteString("  rules:\n")
			sb.WriteString("    - if: $CI_COMMIT_BRANCH == \"main\" && $CI_PIPELINE_SOURCE == \"push\"\n")
		}
	}

	return sb.String()
}
