package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/GoCodeAlone/workflow/config"
	"gopkg.in/yaml.v3"
)

// safeEnvNameRe matches environment names that are safe to embed in shell run
// commands and YAML values. Only alphanumerics, hyphens, underscores, and dots
// are permitted; anything else could inject commands or corrupt the YAML.
var safeEnvNameRe = regexp.MustCompile(`^[a-zA-Z0-9_.\-]+$`)

func runCIInit(args []string) error {
	fs := flag.NewFlagSet("ci init", flag.ContinueOnError)
	platform := fs.String("platform", "github-actions", "CI platform: github-actions, gitlab-ci")
	configFile := fs.String("config", "app.yaml", "Workflow config file")
	output := fs.String("output", "", "Output file path (default: .github/workflows/ci.yml or .gitlab-ci.yml)")
	fs.Usage = func() {
		fmt.Fprintf(fs.Output(), `Usage: wfctl ci init [options]

Generate a bootstrap CI YAML file for the specified CI platform.
The generated file calls wfctl ci run to execute build/test phases.

Options:
`)
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}

	// Read config to detect environments.
	var cfg config.WorkflowConfig
	if data, err := os.ReadFile(*configFile); err == nil {
		_ = yaml.Unmarshal(data, &cfg)
	}

	var content, defaultOutput string
	switch *platform {
	case "github-actions":
		content = generateGHABootstrap(&cfg)
		defaultOutput = ".github/workflows/ci.yml"
	case "gitlab-ci":
		content = generateGitLabCIBootstrap(&cfg)
		defaultOutput = ".gitlab-ci.yml"
	default:
		return fmt.Errorf("unsupported platform %q (supported: github-actions, gitlab-ci)", *platform)
	}

	outPath := *output
	if outPath == "" {
		outPath = defaultOutput
	}

	if err := writeFile(outPath, content); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", outPath)

	// For GitHub Actions, also emit deploy.yml and optional retention.yml.
	if *platform == "github-actions" {
		deployContent := generateGHADeploy(&cfg)
		if deployContent != "" {
			deployPath := ".github/workflows/deploy.yml"
			if err := writeFile(deployPath, deployContent); err != nil {
				return err
			}
			fmt.Printf("wrote %s\n", deployPath)
		}

		retentionContent := generateRetentionYML(&cfg)
		if retentionContent != "" {
			retPath := ".github/workflows/registry-retention.yml"
			if err := writeFile(retPath, retentionContent); err != nil {
				return err
			}
			fmt.Printf("wrote %s\n", retPath)
		}
	}

	return nil
}

func writeFile(path, content string) error {
	if dir := dirOf(path); dir != "" {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return fmt.Errorf("create dir %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// dirOf returns the directory part of a path, or empty string if path has no dir.
func dirOf(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' || path[i] == '\\' {
			return path[:i]
		}
	}
	return ""
}

func generateGHABootstrap(cfg *config.WorkflowConfig) string {
	var sb strings.Builder
	sb.WriteString("# Generated by wfctl ci init -- customize as needed\n")
	sb.WriteString("name: CI/CD\n")
	sb.WriteString("on:\n")
	sb.WriteString("  push:\n")
	sb.WriteString("    branches: [main]\n")
	sb.WriteString("  pull_request:\n")
	sb.WriteString("jobs:\n")
	sb.WriteString("  build-test:\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
	sb.WriteString("      - run: wfctl ci run --phase build,test\n")

	// Emit one deploy job per environment in ci.deploy.environments.
	if cfg != nil && cfg.CI != nil && cfg.CI.Deploy != nil {
		for envName, env := range cfg.CI.Deploy.Environments {
			if env == nil {
				continue
			}
			if !safeEnvNameRe.MatchString(envName) {
				// Skip environments whose names would corrupt the generated YAML or
				// inject shell commands. Names must be [a-zA-Z0-9_.-] only.
				continue
			}
			jobName := "deploy-" + strings.ReplaceAll(envName, ".", "-")
			sb.WriteString("  " + jobName + ":\n")
			sb.WriteString("    runs-on: ubuntu-latest\n")
			sb.WriteString("    needs: [build-test]\n")
			if env.RequireApproval {
				sb.WriteString("    environment: " + envName + "\n")
			}
			sb.WriteString("    steps:\n")
			sb.WriteString("      - uses: actions/checkout@v4\n")
			sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
			sb.WriteString("      - run: wfctl ci run --phase deploy --env " + envName + "\n")
		}
	}

	return sb.String()
}

func generateGitLabCIBootstrap(cfg *config.WorkflowConfig) string {
	var sb strings.Builder
	sb.WriteString("# Generated by wfctl ci init -- customize as needed\n")
	sb.WriteString("stages:\n")
	sb.WriteString("  - build\n")
	sb.WriteString("  - test\n")

	// Add deploy stages for each environment.
	if cfg != nil && cfg.CI != nil && cfg.CI.Deploy != nil {
		for envName := range cfg.CI.Deploy.Environments {
			if !safeEnvNameRe.MatchString(envName) {
				continue
			}
			sb.WriteString("  - deploy-" + strings.ReplaceAll(envName, ".", "-") + "\n")
		}
	}

	sb.WriteString("\nbuild:\n")
	sb.WriteString("  stage: build\n")
	sb.WriteString("  script:\n")
	sb.WriteString("    - wfctl ci run --phase build\n")
	sb.WriteString("  rules:\n")
	sb.WriteString("    - if: $CI_COMMIT_BRANCH == \"main\"\n")
	sb.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")

	sb.WriteString("\ntest:\n")
	sb.WriteString("  stage: test\n")
	sb.WriteString("  needs: [build]\n")
	sb.WriteString("  script:\n")
	sb.WriteString("    - wfctl ci run --phase test\n")
	sb.WriteString("  rules:\n")
	sb.WriteString("    - if: $CI_COMMIT_BRANCH == \"main\"\n")
	sb.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")

	// Emit deploy jobs.
	if cfg != nil && cfg.CI != nil && cfg.CI.Deploy != nil {
		for envName, env := range cfg.CI.Deploy.Environments {
			if env == nil {
				continue
			}
			if !safeEnvNameRe.MatchString(envName) {
				continue
			}
			stageID := strings.ReplaceAll(envName, ".", "-")
			sb.WriteString("\ndeploy-" + stageID + ":\n")
			sb.WriteString("  stage: deploy-" + stageID + "\n")
			sb.WriteString("  needs: [test]\n")
			sb.WriteString("  script:\n")
			sb.WriteString("    - wfctl ci run --phase deploy --env " + envName + "\n")
			if env.RequireApproval {
				sb.WriteString("  when: manual\n")
			}
			sb.WriteString("  rules:\n")
			sb.WriteString("    - if: $CI_COMMIT_BRANCH == \"main\" && $CI_PIPELINE_SOURCE == \"push\"\n")
		}
	}

	return sb.String()
}

// generateGHADeploy emits a minimal ~45-line deploy.yml per design Section 5.
// It uses workflow_run trigger, a build-image job (wfctl build --push), and
// chained deploy-* jobs per ci.deploy.environments.
func generateGHADeploy(cfg *config.WorkflowConfig) string {
	if cfg == nil || cfg.CI == nil {
		return ""
	}
	hasDeploy := cfg.CI.Deploy != nil && len(cfg.CI.Deploy.Environments) > 0
	hasBuild := cfg.CI.Build != nil && len(cfg.CI.Build.Containers) > 0
	if !hasDeploy && !hasBuild {
		return ""
	}

	// Collect registry env vars (sorted) for the build step.
	var regEnvVars []string
	seen := map[string]bool{}
	for _, reg := range cfg.CI.Registries {
		if reg.Auth != nil && reg.Auth.Env != "" && !seen[reg.Auth.Env] {
			regEnvVars = append(regEnvVars, reg.Auth.Env)
			seen[reg.Auth.Env] = true
		}
	}
	if !seen["GITHUB_TOKEN"] {
		regEnvVars = append(regEnvVars, "GITHUB_TOKEN")
	}
	sort.Strings(regEnvVars)

	const sha = "${{ github.event.workflow_run.head_sha || github.sha }}"

	var sb strings.Builder
	sb.WriteString("# Generated by wfctl ci init -- customize as needed\n")
	sb.WriteString("name: Deploy\n")
	sb.WriteString("permissions:\n")
	sb.WriteString("  contents: read\n")
	sb.WriteString("  packages: write\n")
	sb.WriteString("concurrency:\n")
	sb.WriteString("  group: deploy-${{ github.ref }}\n")
	sb.WriteString("  cancel-in-progress: false\n")
	sb.WriteString("on:\n")
	sb.WriteString("  workflow_run:\n")
	sb.WriteString("    workflows: [\"CI\"]\n")
	sb.WriteString("    types: [completed]\n")
	sb.WriteString("    branches: [main]\n")
	sb.WriteString("jobs:\n")
	sb.WriteString("  build-image:\n")
	sb.WriteString("    if: github.event.workflow_run.conclusion == 'success'\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("        with:\n")
	sb.WriteString("          ref: " + sha + "\n")
	sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
	sb.WriteString("      - id: build\n")
	sb.WriteString("        run: wfctl build --push --format json\n")
	if len(regEnvVars) > 0 {
		sb.WriteString("        env:\n")
		for _, envVar := range regEnvVars {
			sb.WriteString("          " + envVar + ": ${{ secrets." + envVar + " }}\n")
		}
	}

	if hasDeploy {
		envNames := sortedEnvNames(cfg.CI.Deploy.Environments)
		prev := "build-image"
		for _, envName := range envNames {
			env := cfg.CI.Deploy.Environments[envName]
			if env == nil || !safeEnvNameRe.MatchString(envName) {
				continue
			}
			jobName := "deploy-" + strings.ReplaceAll(envName, ".", "-")
			sb.WriteString("  " + jobName + ":\n")
			sb.WriteString("    needs: [" + prev + "]\n")
			sb.WriteString("    runs-on: ubuntu-latest\n")
			if env.RequireApproval {
				sb.WriteString("    environment: " + envName + "\n")
			}
			sb.WriteString("    steps:\n")
			sb.WriteString("      - uses: actions/checkout@v4\n")
			sb.WriteString("        with:\n")
			sb.WriteString("          ref: " + sha + "\n")
			sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
			sb.WriteString("      - run: wfctl ci run --phase deploy --env " + envName + "\n")
			prev = jobName
		}
	}

	return sb.String()
}

// generateRetentionYML emits registry-retention.yml when any registry has a
// retention block with a schedule. Returns empty string if not needed.
func generateRetentionYML(cfg *config.WorkflowConfig) string {
	if cfg == nil || cfg.CI == nil {
		return ""
	}

	type retEntry struct {
		name, schedule, envVar string
	}
	var entries []retEntry
	for _, reg := range cfg.CI.Registries {
		if reg.Retention == nil || reg.Retention.Schedule == "" {
			continue
		}
		envVar := ""
		if reg.Auth != nil {
			envVar = reg.Auth.Env
		}
		entries = append(entries, retEntry{reg.Name, reg.Retention.Schedule, envVar})
	}
	if len(entries) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("# Generated by wfctl ci init -- customize as needed\n")
	sb.WriteString("name: Registry Retention\n")
	sb.WriteString("on:\n")
	sb.WriteString("  schedule:\n")
	for _, e := range entries {
		sb.WriteString("    - cron: '" + e.schedule + "'\n")
	}
	sb.WriteString("  workflow_dispatch:\n")
	sb.WriteString("jobs:\n")
	sb.WriteString("  prune:\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("      - uses: GoCodeAlone/setup-wfctl@v1\n")
	for _, e := range entries {
		sb.WriteString("      - run: wfctl registry prune --registry " + e.name + "\n")
		if e.envVar != "" {
			sb.WriteString("        env:\n")
			sb.WriteString("          " + e.envVar + ": ${{ secrets." + e.envVar + " }}\n")
		}
	}

	return sb.String()
}

// sortedEnvNames returns env names with non-approval envs first, then approval envs.
// Each group is sorted alphabetically for stable output.
func sortedEnvNames(envs map[string]*config.CIDeployEnvironment) []string {
	var noApproval, withApproval []string
	for name, env := range envs {
		if env != nil && env.RequireApproval {
			withApproval = append(withApproval, name)
		} else {
			noApproval = append(noApproval, name)
		}
	}
	sort.Strings(noApproval)
	sort.Strings(withApproval)
	return append(noApproval, withApproval...)
}
