package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/GoCodeAlone/workflow/config"
)

// devComposeFileName is the generated docker-compose filename for dev mode.
const devComposeFileName = "docker-compose.dev.yml"

// moduleToDockerImage maps workflow module types to Docker images.
var moduleToDockerImage = map[string]string{
	"database.postgres": "postgres:16",
	"database.workflow": "postgres:16",
	"nosql.redis":       "redis:7-alpine",
	"cache.redis":       "redis:7-alpine",
	"messaging.nats":    "nats:latest",
	"messaging.kafka":   "confluentinc/cp-kafka:latest",
	"messaging.rabbitmq": "rabbitmq:3-management-alpine",
}

// infraModuleEnvDefaults maps module types to default environment variables.
var infraModuleEnvDefaults = map[string]map[string]string{
	"database.postgres": {
		"POSTGRES_USER":     "workflow",
		"POSTGRES_PASSWORD": "workflow",
		"POSTGRES_DB":       "workflow",
	},
	"database.workflow": {
		"POSTGRES_USER":     "workflow",
		"POSTGRES_PASSWORD": "workflow",
		"POSTGRES_DB":       "workflow",
	},
}

// infraModuleVolumes maps module types to volume definitions.
var infraModuleVolumes = map[string]string{
	"database.postgres": "pgdata",
	"database.workflow": "pgdata",
	"nosql.redis":       "redisdata",
	"cache.redis":       "redisdata",
}

// infraModuleVolumeMounts maps module types to container mount paths.
var infraModuleVolumeMounts = map[string]string{
	"database.postgres": "/var/lib/postgresql/data",
	"database.workflow": "/var/lib/postgresql/data",
	"nosql.redis":       "/data",
	"cache.redis":       "/data",
}

// devComposeService represents a docker-compose service entry for dev mode.
type devComposeService struct {
	Image       string               `yaml:"image,omitempty"`
	Build       *devComposeBuild     `yaml:"build,omitempty"`
	Ports       []string             `yaml:"ports,omitempty"`
	Environment map[string]string    `yaml:"environment,omitempty"`
	Volumes     []string             `yaml:"volumes,omitempty"`
	DependsOn   []string             `yaml:"depends_on,omitempty"`
	Restart     string               `yaml:"restart,omitempty"`
	Healthcheck *devComposeHealthcheck `yaml:"healthcheck,omitempty"`
}

type devComposeBuild struct {
	Context    string `yaml:"context,omitempty"`
	Dockerfile string `yaml:"dockerfile,omitempty"`
}

type devComposeHealthcheck struct {
	Test     []string `yaml:"test,omitempty"`
	Interval string   `yaml:"interval,omitempty"`
	Timeout  string   `yaml:"timeout,omitempty"`
	Retries  int      `yaml:"retries,omitempty"`
}

type devComposeSpec struct {
	Services map[string]*devComposeService `yaml:"services"`
	Volumes  map[string]any                `yaml:"volumes,omitempty"`
}

// loadDevConfig loads a WorkflowConfig from the given path, providing a helpful
// error if the file is missing.
func loadDevConfig(cfgPath string) (*config.WorkflowConfig, error) {
	cfg, err := config.LoadFromFile(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("load config %s: %w", cfgPath, err)
	}
	return cfg, nil
}

// generateDevCompose builds a docker-compose.dev.yml from a WorkflowConfig and
// returns the YAML string.
func generateDevCompose(cfg *config.WorkflowConfig) (string, error) {
	cf := &devComposeSpec{
		Services: make(map[string]*devComposeService),
		Volumes:  make(map[string]any),
	}

	infraNames := buildInfraServices(cfg, cf)

	// Build app services.
	if len(cfg.Services) > 0 {
		for svcName, svc := range cfg.Services {
			if svc == nil {
				continue
			}
			appSvc := buildAppService(svcName, svc, infraNames)
			cf.Services[svcName] = appSvc
		}
	} else {
		// Single-service: build a default "app" service.
		appSvc := buildDefaultAppService(cfg, infraNames)
		cf.Services["app"] = appSvc
	}

	data, err := yaml.Marshal(cf)
	if err != nil {
		return "", fmt.Errorf("marshal docker-compose: %w", err)
	}
	return "# Generated by wfctl dev up — do not edit by hand\n" + string(data), nil
}

// buildInfraServices scans cfg.Modules for known infrastructure module types and
// adds corresponding docker-compose service entries. It returns the list of
// infra service names for depends_on wiring.
func buildInfraServices(cfg *config.WorkflowConfig, cf *devComposeSpec) []string {
	var infraNames []string
	seen := map[string]bool{}

	for _, mod := range cfg.Modules {
		image, ok := moduleToDockerImage[mod.Type]
		if !ok {
			continue
		}
		// Deduplicate by image (e.g. two postgres modules → one container).
		svcName := moduleTypeToDNS(mod.Type)
		if seen[svcName] {
			continue
		}
		seen[svcName] = true
		infraNames = append(infraNames, svcName)

		svc := &devComposeService{
			Image:   image,
			Restart: "unless-stopped",
		}

		// Default environment variables.
		if envDefaults, hasEnv := infraModuleEnvDefaults[mod.Type]; hasEnv {
			svc.Environment = make(map[string]string)
			for k, v := range envDefaults {
				svc.Environment[k] = v
			}
		}

		// Port from module config or well-known defaults.
		port := extractInfraPort(mod)
		if port > 0 {
			svc.Ports = []string{fmt.Sprintf("%d:%d", port, port)}
		}

		// Volume mount.
		if volName, hasVol := infraModuleVolumes[mod.Type]; hasVol {
			mountPath := infraModuleVolumeMounts[mod.Type]
			svc.Volumes = []string{fmt.Sprintf("%s:%s", volName, mountPath)}
			cf.Volumes[volName] = nil
		}

		// Healthcheck for postgres.
		if mod.Type == "database.postgres" || mod.Type == "database.workflow" {
			svc.Healthcheck = &devComposeHealthcheck{
				Test:     []string{"CMD-SHELL", "pg_isready -U workflow"},
				Interval: "5s",
				Timeout:  "5s",
				Retries:  10,
			}
		}

		cf.Services[svcName] = svc
	}
	return infraNames
}

// buildAppService creates a compose service entry for a named service.
func buildAppService(name string, svc *config.ServiceConfig, infraNames []string) *devComposeService {
	cs := &devComposeService{
		DependsOn: infraNames,
		Restart:   "unless-stopped",
	}

	if fileExists("Dockerfile") {
		cs.Build = &devComposeBuild{Context: ".", Dockerfile: "Dockerfile"}
	} else {
		cs.Image = name + ":dev"
	}

	for _, exp := range svc.Expose {
		port := exp.Port
		cs.Ports = append(cs.Ports, fmt.Sprintf("%d:%d", port, port))
	}
	return cs
}

// buildDefaultAppService creates a single "app" service when no services: section exists.
func buildDefaultAppService(cfg *config.WorkflowConfig, infraNames []string) *devComposeService {
	cs := &devComposeService{
		DependsOn: infraNames,
		Restart:   "unless-stopped",
	}
	if fileExists("Dockerfile") {
		cs.Build = &devComposeBuild{Context: ".", Dockerfile: "Dockerfile"}
	} else {
		cs.Image = "app:dev"
	}
	// Detect http.server module ports.
	for _, mod := range cfg.Modules {
		if mod.Type == "http.server" || mod.Type == "http.router" {
			port, _ := extractModulePort(mod)
			if port > 0 {
				cs.Ports = append(cs.Ports, fmt.Sprintf("%d:%d", port, port))
			}
		}
	}
	return cs
}

// extractInfraPort returns the default port for known infra module types.
func extractInfraPort(mod config.ModuleConfig) int {
	switch mod.Type {
	case "database.postgres", "database.workflow":
		return 5432
	case "nosql.redis", "cache.redis":
		return 6379
	case "messaging.nats":
		return 4222
	case "messaging.kafka":
		return 9092
	case "messaging.rabbitmq":
		return 5672
	}
	return 0
}

// moduleTypeToDNS converts a module type like "database.postgres" to a
// DNS-safe service name like "postgres".
func moduleTypeToDNS(modType string) string {
	parts := strings.Split(modType, ".")
	last := parts[len(parts)-1]
	// Shorten well-known names.
	switch last {
	case "workflow":
		return "postgres"
	}
	return last
}

// runDevCompose generates docker-compose.dev.yml and runs docker compose up -d.
func runDevCompose(cfg *config.WorkflowConfig, cfgPath string, verbose bool) error {
	composeYAML, err := generateDevCompose(cfg)
	if err != nil {
		return fmt.Errorf("generate compose: %w", err)
	}

	// Write to the same directory as the config file.
	outDir := filepath.Dir(cfgPath)
	outPath := filepath.Join(outDir, devComposeFileName)
	if err := os.WriteFile(outPath, []byte(composeYAML), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("Generated %s\n", outPath)

	args := []string{"compose", "-f", outPath, "up", "-d"}
	cmd := exec.Command("docker", args...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if verbose {
		fmt.Printf("Running: docker %s\n", strings.Join(args, " "))
	}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker compose up: %w", err)
	}
	fmt.Println("Development cluster started. Run 'wfctl dev status' to check health.")
	return nil
}

// devComposeDown stops the docker-compose dev cluster.
func devComposeDown(verbose bool) error {
	outPath := devComposeFileName
	if !fileExists(outPath) {
		return fmt.Errorf("%s not found; run 'wfctl dev up' first", outPath)
	}
	args := []string{"compose", "-f", outPath, "down"}
	cmd := exec.Command("docker", args...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if verbose {
		fmt.Printf("Running: docker %s\n", strings.Join(args, " "))
	}
	return cmd.Run()
}

// devComposeLogs streams logs from the compose cluster.
func devComposeLogs(service string, follow bool) error {
	args := []string{"compose", "-f", devComposeFileName, "logs"}
	if follow {
		args = append(args, "--follow")
	}
	if service != "" {
		args = append(args, service)
	}
	cmd := exec.Command("docker", args...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// devComposeStatus shows the running state of compose services.
func devComposeStatus() error {
	args := []string{"compose", "-f", devComposeFileName, "ps"}
	cmd := exec.Command("docker", args...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// devComposeRestart restarts a compose service.
func devComposeRestart(service string) error {
	args := []string{"compose", "-f", devComposeFileName, "restart"}
	if service != "" {
		args = append(args, service)
	}
	cmd := exec.Command("docker", args...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
