package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/GoCodeAlone/workflow/secrets"
)

// devSecretsEnvFileName is the temp env file written when --secrets-from is set.
const devSecretsEnvFileName = ".env.wfctl-dev-secrets" //nolint:gosec // G101: this is a filename, not a credential

// writeDevSecretsEnvFile resolves all secrets from the named ad-hoc provider
// and writes them as KEY=value lines to <dir>/.env.wfctl-dev-secrets (mode 0600).
// It returns the absolute path to the written file.
func writeDevSecretsEnvFile(providerName, service, dir string) (string, error) {
	p, err := buildAdhocProvider(providerName, service)
	if err != nil {
		return "", err
	}

	ctx := context.Background()
	keys, err := p.List(ctx)
	if err != nil {
		if errors.Is(err, secrets.ErrUnsupported) {
			return "", fmt.Errorf("provider %q does not support listing; use --secrets-service to set a prefix (e.g. --secrets-service MY_APP_)", providerName)
		}
		return "", fmt.Errorf("list secrets from provider %q: %w", providerName, err)
	}

	var buf strings.Builder
	buf.WriteString("# Generated by wfctl dev up — do not commit\n")
	for _, key := range keys {
		val, err := exportGetValue(ctx, providerName, p, key)
		if err != nil {
			fmt.Fprintf(&buf, "# SKIP %s: %v\n", key, err)
			continue
		}
		fmt.Fprintf(&buf, "%s=%s\n", key, val)
	}

	path := filepath.Join(dir, devSecretsEnvFileName)
	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	return path, nil
}

// removeDevSecretsEnvFile removes the temp secrets env file, ignoring not-found errors.
func removeDevSecretsEnvFile(path string) error {
	err := os.Remove(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}
