package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/GoCodeAlone/workflow/config"
	"github.com/GoCodeAlone/workflow/interfaces"
	"github.com/GoCodeAlone/workflow/secrets"
)

// multiStringFlag is a flag.Value that collects repeated --flag values and
// splits each value on commas, so both --force-rotate A,B and
// --force-rotate A --force-rotate B are equivalent.
type multiStringFlag []string

func (f *multiStringFlag) String() string { return strings.Join(*f, ",") }

func (f *multiStringFlag) Set(v string) error {
	for _, part := range strings.Split(v, ",") {
		part = strings.TrimSpace(part)
		if part != "" {
			*f = append(*f, part)
		}
	}
	return nil
}

// isRotatableType returns true for secret types that wfctl can regenerate
// locally. provider_credential rotation requires the upstream provider plugin
// to revoke the old credential (mint-new-then-revoke-old; see ADR 0012).
// infra_output types are derived from apply-time state and are never
// generated by bootstrap at all.
func isRotatableType(t string) bool {
	switch t {
	case "random_hex", "random_base64", "random_alphanumeric", "provider_credential":
		return true
	default:
		return false
	}
}

func runInfraBootstrap(args []string) error {
	fs := flag.NewFlagSet("infra bootstrap", flag.ContinueOnError)
	var configFile string
	fs.StringVar(&configFile, "config", "", "Config file")
	fs.StringVar(&configFile, "c", "", "Config file (short for --config)")
	var envName string
	fs.StringVar(&envName, "env", "", "Environment name (resolves per-module environments: overrides)")
	var rotateNames multiStringFlag
	fs.Var(&rotateNames, "force-rotate", "Comma-separated list of secret names to regenerate, replacing existing values. Repeatable. Use for recovery from known-bad secrets (empty value, leak, etc).")
	if err := fs.Parse(args); err != nil {
		return err
	}

	cfgFile, err := resolveInfraConfig(fs, configFile)
	if err != nil {
		return err
	}

	// originalCfgFile is used for parseSecretsConfig so that the secrets.generate[]
	// block is always read from the original YAML. writeEnvResolvedConfig marshals
	// via config.WorkflowConfig which has no Generate field, so the generate[] section
	// would be silently dropped from the env-resolved temp file.
	originalCfgFile := cfgFile

	// If --env is set, resolve the config for that environment before bootstrapping.
	// cfgFile is reassigned to the temp path; originalCfgFile retains the original.
	if envName != "" {
		tmp, resErr := writeEnvResolvedConfig(cfgFile, envName)
		if resErr != nil {
			return resErr
		}
		defer os.Remove(tmp)
		cfgFile = tmp
	}

	ctx := context.Background()

	// 1. Generate and store secrets FIRST so that state-backend access keys are
	//    available in the current process environment before bootstrapStateBackend
	//    runs. (Remote bucket creation requires API auth with the provider key pair,
	//    which is generated here via the provider_credential source.)
	// Use originalCfgFile — not cfgFile — so the generate[] block is not lost
	// in the env-resolved temp file's round-trip through config.WorkflowConfig.
	secretsCfg, err := parseSecretsConfig(originalCfgFile)
	if err != nil {
		return fmt.Errorf("parse secrets config: %w", err)
	}

	// Build the force-rotate set (deduped). Validate all names against
	// secrets.generate[] before touching the store — fast-fail on typos.
	forceRotate, err := buildForceRotateSet(rotateNames, secretsCfg)
	if err != nil {
		return err
	}

	if secretsCfg != nil && len(secretsCfg.Generate) > 0 {
		provider, err := resolveSecretsProvider(secretsCfg)
		if err != nil {
			return fmt.Errorf("resolve secrets provider: %w", err)
		}

		// Load the IaC provider for ProviderCredentialRevoker if any force-rotate
		// target is a provider_credential type. We do this lazily (only when needed)
		// so that runs without --force-rotate on provider_credential don't require
		// the plugin binary to be installed.
		revoker, iacCloser := resolveCredentialRevoker(ctx, cfgFile, secretsCfg, forceRotate)
		if iacCloser != nil {
			defer iacCloser.Close() //nolint:errcheck
		}

		generated, err := bootstrapSecrets(ctx, provider, secretsCfg, forceRotate, revoker)
		if err != nil {
			return err
		}
		// Export freshly generated secrets to the current process environment so
		// that bootstrapStateBackend can read them via ${VAR} expansion in the
		// module config (e.g. accessKey: "${PROVIDER_access_key}").
		for k, v := range generated {
			os.Setenv(k, v) //nolint:errcheck
		}
	} else {
		fmt.Println("No secrets to generate.")
	}

	// 2. Bootstrap state backend (uses provider keys now in env from step 1).
	if err := bootstrapStateBackend(ctx, cfgFile); err != nil {
		return fmt.Errorf("bootstrap state backend: %w", err)
	}

	return nil
}

// buildForceRotateSet validates each name in rotateNames against
// secretsCfg.Generate and returns a map[name]bool for O(1) lookup.
// It returns an error if:
//   - a name has no matching secrets.generate[] entry (typo guard)
//   - a name refers to an infra_output type (never generated by bootstrap)
func buildForceRotateSet(names []string, cfg *SecretsConfig) (map[string]bool, error) {
	if len(names) == 0 {
		return nil, nil
	}

	// Index secrets.generate[] by key for O(1) validation.
	byKey := make(map[string]SecretGen)
	if cfg != nil {
		for _, gen := range cfg.Generate {
			byKey[gen.Key] = gen
		}
	}

	set := make(map[string]bool, len(names))
	for _, name := range names {
		gen, ok := byKey[name]
		if !ok {
			return nil, fmt.Errorf("no secrets.generate entry named %q in infra.yaml", name)
		}
		if !isRotatableType(gen.Type) {
			return nil, fmt.Errorf("--force-rotate %q: %s secrets are derived from apply-time state and cannot be regenerated by bootstrap", name, gen.Type)
		}
		set[name] = true
	}
	return set, nil
}

// bootstrapStateBackend checks the iac.state config and creates any required
// backing infrastructure for the configured backend. It dispatches by the
// backend type declared in the iac.state module:
//
//   - filesystem / memory / postgres / "" → no-op (no remote bucket required)
//   - any other backend → dispatched through the IaCProvider plugin via
//     provider.BootstrapStateBackend(ctx, iacStateConfig)
//
// ${VAR} / $VAR references in the module config are expanded before the config
// is passed to the provider, so secrets can be injected via the environment.
//
// On success, each entry in result.EnvVars is printed as `export KEY=VALUE`
// for CI capture, and result.Bucket is written back to the on-disk config so
// downstream commands can load state without the env var being set again.
func bootstrapStateBackend(ctx context.Context, cfgFile string) error {
	iacStates, _, _, err := discoverInfraModules(cfgFile)
	if err != nil {
		return fmt.Errorf("discover infra modules: %w", err)
	}
	if len(iacStates) == 0 {
		return nil
	}
	m := iacStates[0]
	// Expand ${VAR} / $VAR references before reading individual fields.
	cfg := config.ExpandEnvInMap(m.Config)
	backend, _ := cfg["backend"].(string)

	// Self-contained backends don't require a remote bucket to be created.
	switch backend {
	case "filesystem", "memory", "postgres", "":
		return nil
	}

	// For remote backends, dispatch through the IaCProvider plugin interface.
	// Find the first iac.provider module declared in the config.
	rawCfg, err := config.LoadFromFile(cfgFile)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	var provType string
	var provCfg map[string]any
	for i := range rawCfg.Modules {
		mod := &rawCfg.Modules[i]
		if mod.Type != "iac.provider" {
			continue
		}
		modCfg := config.ExpandEnvInMap(mod.Config)
		if pt, ok := modCfg["provider"].(string); ok && pt != "" {
			provType = pt
			provCfg = modCfg
			break
		}
	}
	if provType == "" {
		return fmt.Errorf("no iac.provider module found in config — add an iac.provider module to bootstrap remote state backends (backend=%q)", backend)
	}

	provider, closer, err := resolveIaCProvider(ctx, provType, provCfg)
	if err != nil {
		return fmt.Errorf("load provider %q for state backend bootstrap: %w", provType, err)
	}
	if closer != nil {
		pType := provType
		defer func() {
			if cerr := closer.Close(); cerr != nil {
				fmt.Fprintf(os.Stderr, "warning: provider %q shutdown: %v\n", pType, cerr)
			}
		}()
	}

	result, err := provider.BootstrapStateBackend(ctx, cfg)
	if err != nil {
		return fmt.Errorf("bootstrap state backend (backend=%q, provider=%q): %w", backend, provType, err)
	}
	if result == nil {
		return nil
	}

	// Ensure WFCTL_STATE_BUCKET is always present when a bucket was returned.
	if result.Bucket != "" {
		if result.EnvVars == nil {
			result.EnvVars = make(map[string]string)
		}
		if result.EnvVars["WFCTL_STATE_BUCKET"] == "" {
			result.EnvVars["WFCTL_STATE_BUCKET"] = result.Bucket
		}
	}

	// Print export lines in stable order for CI capture (e.g. $GITHUB_ENV).
	keys := make([]string, 0, len(result.EnvVars))
	for k := range result.EnvVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Printf("export %s=%s\n", k, result.EnvVars[k])
	}

	// Write the resolved bucket name back to the on-disk config so downstream
	// wfctl commands can load state without the env var being set again.
	if result.Bucket != "" {
		if writeErr := writeBucketBackToConfig(cfgFile, result.Bucket); writeErr != nil {
			// Non-fatal: bucket exists; warn and continue.
			fmt.Printf("WARNING: could not write bucket back to config: %v\n", writeErr)
		}
	}
	return nil
}

// resolveCredentialRevoker checks whether any force-rotate target is a
// provider_credential type and, if so, loads the IaC provider plugin and
// returns a ProviderCredentialRevoker (if the plugin supports it) and an
// io.Closer for the plugin process. Returns (nil, nil) when no
// provider_credential rotation is requested or the provider doesn't implement
// ProviderCredentialRevoker (a warning is logged in that case).
//
// The returned Closer (if non-nil) must be closed by the caller — it MUST NOT
// be deferred inside a loop; callers should defer it at the function scope.
func resolveCredentialRevoker(ctx context.Context, cfgFile string, secretsCfg *SecretsConfig, forceRotate map[string]bool) (interfaces.ProviderCredentialRevoker, interface{ Close() error }) {
	if len(forceRotate) == 0 || secretsCfg == nil {
		return nil, nil
	}
	// Check if any force-rotate target is provider_credential.
	needsRevoker := false
	for _, gen := range secretsCfg.Generate {
		if forceRotate[gen.Key] && gen.Type == "provider_credential" {
			needsRevoker = true
			break
		}
	}
	if !needsRevoker {
		return nil, nil
	}

	iacProv, iacCloser, loadErr := loadIaCProviderFromConfig(ctx, cfgFile)
	if loadErr != nil {
		// Non-fatal: log warning; credential will still be minted but old one
		// won't be automatically revoked at the upstream provider.
		fmt.Fprintf(os.Stderr, "warn: could not load IaC provider for credential revocation: %v\n", loadErr)
		fmt.Fprintf(os.Stderr, "warn: old provider credential will NOT be revoked automatically — revoke manually\n")
		return nil, nil
	}
	if iacProv == nil {
		// No iac.provider module in config.
		fmt.Fprintf(os.Stderr, "warn: no iac.provider module in config — old provider credential will NOT be revoked automatically\n")
		return nil, nil
	}
	r, ok := iacProv.(interfaces.ProviderCredentialRevoker)
	if !ok {
		fmt.Fprintf(os.Stderr, "warn: IaC provider does not implement ProviderCredentialRevoker — old credential will NOT be revoked automatically\n")
		return nil, iacCloser
	}
	return r, iacCloser
}

// loadIaCProviderFromConfig finds the first iac.provider module in cfgFile,
// loads the provider plugin, and returns it. Returns (nil, nil, nil) when no
// iac.provider module is declared (caller treats as "provider not available").
// The returned io.Closer (if non-nil) must be closed by the caller.
func loadIaCProviderFromConfig(ctx context.Context, cfgFile string) (interfaces.IaCProvider, interface{ Close() error }, error) {
	rawCfg, err := config.LoadFromFile(cfgFile)
	if err != nil {
		return nil, nil, fmt.Errorf("load config: %w", err)
	}
	var provType string
	var provCfg map[string]any
	for i := range rawCfg.Modules {
		mod := &rawCfg.Modules[i]
		if mod.Type != "iac.provider" {
			continue
		}
		modCfg := config.ExpandEnvInMap(mod.Config)
		if pt, ok := modCfg["provider"].(string); ok && pt != "" {
			provType = pt
			provCfg = modCfg
			break
		}
	}
	if provType == "" {
		return nil, nil, nil // no iac.provider module in config
	}
	prov, closer, err := resolveIaCProvider(ctx, provType, provCfg)
	if err != nil {
		return nil, nil, fmt.Errorf("load provider %q: %w", provType, err)
	}
	return prov, closer, nil
}

// writeBucketBackToConfig rewrites the iac.state module's `bucket:` field in
// cfgFile with the resolved bucket name. It is backend-neutral — the same
// field name is used by all remote backends (spaces, s3, gcs, azure). It uses
// a line-level text replacement to preserve YAML formatting, comments, and
// indentation.
func writeBucketBackToConfig(cfgFile, bucket string) error {
	data, err := os.ReadFile(cfgFile)
	if err != nil {
		return fmt.Errorf("read config: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	inIACState := false
	bucketReplaced := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Track when we enter an iac.state module block.
		if strings.Contains(trimmed, "type: iac.state") {
			inIACState = true
		}
		// Leave the block when we encounter the next top-level module entry.
		if inIACState && strings.HasPrefix(trimmed, "- name:") {
			inIACState = false
		}

		if inIACState && strings.HasPrefix(trimmed, "bucket:") {
			// Preserve leading whitespace from the original line.
			indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
			lines[i] = indent + "bucket: " + bucket
			bucketReplaced = true
		}
	}

	if !bucketReplaced {
		// Nothing to replace — bucket field not present or already correct.
		return nil
	}

	return os.WriteFile(cfgFile, []byte(strings.Join(lines, "\n")), 0o600)
}

// providerCredentialSubKeys lists the sub-key names produced by each
// provider_credential source. Existence checks must verify ALL of them so a
// partial prior write (e.g. one sub-key manually deleted) triggers a full
// regeneration rather than an incorrect skip.
//
// TODO(follow-up #29): this map is hard-coded for DO Spaces. It should be
// registered by provider plugins via a hook (e.g. CredentialSubKeys() method
// on EnginePlugin) so that third-party providers can declare their own sub-keys
// without modifying wfctl core.
var providerCredentialSubKeys = map[string][]string{
	"digitalocean.spaces": {"access_key", "secret_key"},
}

// subKeysForSource returns the sub-key names for a given provider_credential
// source (e.g. "digitalocean.spaces" → ["access_key", "secret_key"]).
// Returns nil, false when the source is not registered.
func subKeysForSource(source string) ([]string, bool) {
	subs, ok := providerCredentialSubKeys[source]
	return subs, ok
}

// generateSecret is the package-level hook used by bootstrapSecrets. Tests
// override it to exercise provider_credential code paths without reaching
// out to cloud APIs.
var generateSecret = secrets.GenerateSecret

// expectedStoredKeys returns every key name that a completed generation of
// gen would have stored in the provider. For provider_credential with a
// known source, that is "<key>_<subkey>" for each subkey; for simple
// generators it is just gen.Key.
func expectedStoredKeys(gen SecretGen) []string {
	if gen.Type == "provider_credential" {
		if subs, ok := providerCredentialSubKeys[gen.Source]; ok {
			out := make([]string, len(subs))
			for i, s := range subs {
				out[i] = gen.Key + "_" + s
			}
			return out
		}
		// Unknown source — best-effort single probe.
		return []string{gen.Key + "_access_key"}
	}
	return []string{gen.Key}
}

// bootstrapSecrets generates and stores secrets that don't already exist.
// It returns a map of every key-value pair that was newly generated in this
// run (skipped/pre-existing keys are NOT included). The caller can export
// these to the process environment for downstream steps.
//
// forceRotate is an optional set of secret keys to regenerate even when the
// secret already exists. The function deletes the existing value before
// re-creating it (best-effort delete: a missing secret is logged as a warning
// and treated as the "no pre-existing value" case). After rotation the audit
// line is written to stderr.
//
// revoker is an optional ProviderCredentialRevoker. When non-nil and a
// provider_credential is being force-rotated, the OLD credential is revoked at
// the upstream provider AFTER the new credential has been minted and stored
// (mint-new-then-revoke-old; see ADR 0012). If revoker is nil, the old
// credential is not explicitly revoked (operator must revoke manually).
func bootstrapSecrets(ctx context.Context, provider secrets.Provider, cfg *SecretsConfig, forceRotate map[string]bool, revoker ...interfaces.ProviderCredentialRevoker) (map[string]string, error) {
	var credRevoker interfaces.ProviderCredentialRevoker
	if len(revoker) > 0 {
		credRevoker = revoker[0]
	}
	generated := map[string]string{}

	// Cache List() as a set so repeated probes in a bootstrap run only hit
	// the provider once and subsequent lookups are O(1). Resolved lazily on
	// the first write-only Get.
	var listSet map[string]struct{}
	var listErr error
	var listDone bool
	lookupViaList := func(key string) (bool, error) {
		if !listDone {
			names, err := provider.List(ctx)
			listErr = err
			if err == nil {
				listSet = make(map[string]struct{}, len(names))
				for _, n := range names {
					listSet[n] = struct{}{}
				}
			}
			listDone = true
		}
		if listErr != nil && !errors.Is(listErr, secrets.ErrUnsupported) {
			return false, fmt.Errorf("list secrets to check %q: %w", key, listErr)
		}
		_, ok := listSet[key]
		return ok, nil
	}
	secretExists := func(key string) (bool, error) {
		_, err := provider.Get(ctx, key)
		switch {
		case err == nil:
			return true, nil
		case errors.Is(err, secrets.ErrNotFound):
			return false, nil
		case errors.Is(err, secrets.ErrUnsupported):
			return lookupViaList(key)
		default:
			return false, fmt.Errorf("check secret %q: %w", key, err)
		}
	}

	for _, gen := range cfg.Generate {
		// infra_output secrets depend on apply-time state; skip during bootstrap.
		if gen.Type == "infra_output" {
			continue
		}

		// Build generator config from SecretGen fields.
		genConfig := map[string]any{}
		if gen.Length > 0 {
			genConfig["length"] = gen.Length
		}
		if gen.Source != "" {
			genConfig["source"] = gen.Source
		}

		// --force-rotate path: for provider_credential, read the OLD access_key_id
		// BEFORE deleting so we can revoke it at the upstream provider after minting
		// the new one (mint-new-then-revoke-old; see ADR 0012).
		// For other types, delete the existing value (best-effort) so that the
		// normal "doesn't exist → generate + create" code path runs below.
		var oldCredentialID string // non-empty only for provider_credential + force-rotate
		if forceRotate[gen.Key] {
			if gen.Type == "provider_credential" && credRevoker != nil {
				// Read old access_key sub-key before deletion.
				accessKeyName := gen.Key + "_access_key"
				if oldVal, getErr := provider.Get(ctx, accessKeyName); getErr == nil {
					oldCredentialID = oldVal
				}
				// Delete all sub-keys for this provider_credential.
				subKeys, hasSubKeys := subKeysForSource(gen.Source)
				if hasSubKeys {
					for _, sub := range subKeys {
						fullKey := gen.Key + "_" + sub
						if delErr := provider.Delete(ctx, fullKey); delErr != nil {
							fmt.Fprintf(os.Stderr, "warn: rotate-pre-delete %s: %v (continuing)\n", fullKey, delErr)
						}
					}
				} else {
					// Unknown source — best-effort single delete.
					if delErr := provider.Delete(ctx, accessKeyName); delErr != nil {
						fmt.Fprintf(os.Stderr, "warn: rotate-pre-delete %s: %v (continuing)\n", accessKeyName, delErr)
					}
				}
			} else {
				deleteKey := gen.Key
				if delErr := provider.Delete(ctx, deleteKey); delErr != nil {
					// Log and continue regardless of the error kind — both absent/unsupported
					// secrets and unexpected errors should not block the rotation flow.
					fmt.Fprintf(os.Stderr, "warn: rotate-pre-delete %s: %v (continuing)\n", deleteKey, delErr)
				}
			}
			// Invalidate the List cache so the existence check below reflects the
			// deletion. A fresh List call after Delete is the safe path for
			// write-only providers (GitHub Actions) where Get is unsupported.
			listDone = false
			listSet = nil
		} else {
			// Normal path: check that EVERY expected stored key is already present
			// before skipping. provider_credential writes multiple sub-keys; if a
			// prior write was partial or one sub-key was manually removed, we must
			// regenerate to produce a usable credential. Without this loop, every
			// run regenerates for write-only providers (GH Actions), and
			// provider_credential regeneration orphans upstream credentials.
			expected := expectedStoredKeys(gen)
			allExist := true
			for _, key := range expected {
				present, err := secretExists(key)
				if err != nil {
					return generated, err
				}
				if !present {
					allExist = false
					break
				}
			}
			if allExist {
				fmt.Printf("  secret %q: already exists — skipped\n", gen.Key)
				continue
			}
		}

		// Generate the secret value.
		value, err := generateSecret(ctx, gen.Type, genConfig)
		if err != nil {
			return generated, fmt.Errorf("generate secret %q: %w", gen.Key, err)
		}

		// For provider_credential results (JSON map), store each sub-key.
		if gen.Type == "provider_credential" {
			var subKeyMap map[string]string
			if jsonErr := json.Unmarshal([]byte(value), &subKeyMap); jsonErr == nil {
				for subKey, subVal := range subKeyMap {
					fullKey := gen.Key + "_" + subKey
					if setErr := provider.Set(ctx, fullKey, subVal); setErr != nil {
						return generated, fmt.Errorf("store secret %q: %w", fullKey, setErr)
					}
					generated[fullKey] = subVal
					if forceRotate[gen.Key] {
						fmt.Printf("  secret %q: rotated\n", fullKey)
					} else {
						fmt.Printf("  secret %q: created\n", fullKey)
					}
				}
				if forceRotate[gen.Key] {
					fmt.Fprintf(os.Stderr, "wfctl: rotated provider_credential %s (replaced existing value at %s)\n", gen.Key, time.Now().UTC().Format(time.RFC3339))
					// Revoke the OLD credential at the upstream provider AFTER storing
					// the new one. Failure is non-fatal: the new credential is valid and
					// must not be rolled back. Log warning + continue (see ADR 0012).
					if credRevoker != nil && oldCredentialID != "" {
						if revokeErr := credRevoker.RevokeProviderCredential(ctx, gen.Source, oldCredentialID); revokeErr != nil {
							fmt.Fprintf(os.Stderr, "warn: revoke old credential %s (id=%s): %v — revoke manually\n", gen.Key, oldCredentialID, revokeErr)
						} else {
							fmt.Fprintf(os.Stderr, "wfctl: revoked old credential %s (id=%s)\n", gen.Key, oldCredentialID)
						}
					} else if credRevoker == nil && oldCredentialID != "" {
						fmt.Fprintf(os.Stderr, "warn: no revoker available — old credential %s (id=%s) must be revoked manually\n", gen.Key, oldCredentialID)
					}
				}
				continue
			}
		}

		if err := provider.Set(ctx, gen.Key, value); err != nil {
			return generated, fmt.Errorf("store secret %q: %w", gen.Key, err)
		}
		generated[gen.Key] = value

		if forceRotate[gen.Key] {
			fmt.Printf("  secret %q: rotated\n", gen.Key)
			fmt.Fprintf(os.Stderr, "wfctl: rotated secret %s (replaced existing value at %s)\n", gen.Key, time.Now().UTC().Format(time.RFC3339))
		} else {
			fmt.Printf("  secret %q: created\n", gen.Key)
		}
	}
	return generated, nil
}
