# E-Commerce Store Application Configuration
# A full-stack e-commerce application demonstrating the Workflow engine's ability
# to compose an entire web application from declarative YAML configuration.
#
# Architecture:
#   SPA (static files) + REST API + JWT auth + order state machine + event messaging
#   + dynamic processing components (inventory, payment, shipping, notifications)
#   + SQLite persistence + Prometheus metrics
#
# Data flow:
#   Browser -> SPA (static.fileserver) -> /api/* (router) -> middleware chain
#   -> api.handler -> statemachine.engine -> processing.step -> dynamic.component
#   -> messaging.broker -> notification handler
#
# Processing pipeline:
#   POST /api/orders -> new -> start_validation -> validating
#   -> [inventory-checker] -> validation_passed -> validated
#   -> [event: order.validated] -> start_payment -> paying
#   -> [payment-processor] -> payment_approved -> paid
#   -> [event: order.paid] -> start_shipping -> shipping
#   -> [shipping-service] -> shipping_confirmed -> shipped -> delivered
#
# Failure paths:
#   validating -> [inventory check fails] -> validation_failed -> failed
#   paying -> [payment declined] -> payment_declined -> payment_failed
#   payment_failed -> retry_payment -> paying (max retries)
#   shipping -> [shipping fails] -> shipping_failed -> ship_failed
#   ship_failed -> retry_shipping -> shipping (max retries)
#
# Public endpoints:  GET /api/products, POST /api/auth/login, POST /api/auth/register
# Protected endpoints: POST/GET /api/orders, GET /api/orders/{id}
# Observability: GET /healthz, GET /metrics

modules:
  # --- HTTP infrastructure ---
  - name: web-server
    type: http.server
    config:
      address: ":8080"
      readTimeout: "15s"
      writeTimeout: "15s"

  - name: router
    type: http.router
    config:
      prefix: /api
    dependsOn:
      - web-server

  # --- Middleware chain ---
  - name: cors
    type: http.middleware.cors
    config:
      allowedOrigins: ["*"]
      allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowedHeaders: ["Content-Type", "Authorization"]
    dependsOn:
      - router

  - name: request-id
    type: http.middleware.requestid
    dependsOn:
      - cors

  - name: rate-limiter
    type: http.middleware.ratelimit
    config:
      requestsPerMinute: 300
      burstSize: 50
    dependsOn:
      - request-id

  # --- Authentication ---
  - name: auth
    type: auth.jwt
    config:
      secret: "${JWT_SECRET}"
      tokenExpiry: "24h"
      issuer: "workflow-store"
    dependsOn:
      - rate-limiter

  - name: auth-middleware
    type: http.middleware.auth
    config:
      authType: Bearer
    dependsOn:
      - auth

  # --- API handlers ---
  - name: products-api
    type: api.handler
    config:
      resourceName: products
      seedFile: "./seed/products.json"
    dependsOn:
      - rate-limiter

  - name: orders-api
    type: api.handler
    config:
      resourceName: orders
      workflowType: "order-processing"
      workflowEngine: "order-state"
      instanceIDPrefix: "order-"
      instanceIDField: "id"
    dependsOn:
      - auth-middleware
      - persistence

  # --- Order state machine ---
  - name: order-state
    type: statemachine.engine
    config:
      description: "Manages order lifecycle state transitions"
    dependsOn:
      - orders-api

  # --- Persistence ---
  - name: order-db
    type: database.workflow
    config:
      driver: "sqlite"
      dsn: "./data/ecommerce.db"

  - name: persistence
    type: persistence.store
    config:
      database: "order-db"
    dependsOn:
      - order-db

  # --- Dynamic processing components ---
  # These simulate real-world integrations (payment gateways, shipping APIs, etc.)
  # In production, these would call actual third-party APIs.

  - name: inventory-checker
    type: dynamic.component
    config:
      source: "./components/inventory_checker.go"
      description: "Simulates warehouse inventory check (real-world: ShipBob, Fulfil.io API)"
    dependsOn:
      - order-state

  - name: payment-processor
    type: dynamic.component
    config:
      source: "./components/payment_processor.go"
      description: "Simulates payment gateway (real-world: Stripe, PayPal API)"
    dependsOn:
      - order-state

  - name: shipping-service
    type: dynamic.component
    config:
      source: "./components/shipping_service.go"
      description: "Simulates shipping label generation (real-world: EasyPost, ShipStation API)"
    dependsOn:
      - order-state

  - name: notification-sender
    type: dynamic.component
    config:
      source: "./components/notification_sender.go"
      description: "Simulates email/SMS notifications (real-world: SendGrid, Twilio, SNS)"
    dependsOn:
      - order-state

  # --- Processing steps (bridge: dynamic component -> state machine) ---
  # Each processing step wraps a dynamic component with retry logic and
  # fires success/compensation transitions based on the component's result.

  - name: step-validate
    type: processing.step
    config:
      componentId: "inventory-checker"
      successTransition: "validation_passed"
      compensateTransition: "validation_failed"
      maxRetries: 1
      retryBackoffMs: 500
      timeoutSeconds: 10
    dependsOn:
      - inventory-checker
      - order-state

  - name: step-payment
    type: processing.step
    config:
      componentId: "payment-processor"
      successTransition: "payment_approved"
      compensateTransition: "payment_declined"
      maxRetries: 2
      retryBackoffMs: 1000
      timeoutSeconds: 30
    dependsOn:
      - payment-processor
      - order-state

  - name: step-shipping
    type: processing.step
    config:
      componentId: "shipping-service"
      successTransition: "shipping_confirmed"
      compensateTransition: "shipping_failed"
      maxRetries: 2
      retryBackoffMs: 2000
      timeoutSeconds: 30
    dependsOn:
      - shipping-service
      - order-state

  # --- Messaging ---
  - name: event-broker
    type: messaging.broker
    config:
      topics:
        - "order.created"
        - "order.validated"
        - "order.paid"
        - "order.shipped"
        - "order.delivered"
        - "order.cancelled"
        - "order.failed"
        - "order.payment_failed"
        - "order.ship_failed"
    dependsOn:
      - order-state

  - name: notification-handler
    type: messaging.handler
    config:
      topic: "order.*"
      description: "Handles notifications for all order lifecycle events"
    dependsOn:
      - event-broker

  # --- Observability ---
  - name: metrics
    type: metrics.collector
    config:
      namespace: ecommerce

  - name: health
    type: health.checker
    config:
      description: "Health, readiness, and liveness probes"

  # --- Static file serving (SPA) ---
  - name: spa
    type: static.fileserver
    config:
      root: "./spa"
      prefix: "/"
      spaFallback: true
      cacheMaxAge: 3600
    dependsOn:
      - web-server

# --- Workflow definitions ---
workflows:
  # HTTP routing
  http:
    router: router
    server: web-server
    routes:
      # Public: product catalog (read-only)
      - method: "GET"
        path: "/api/products"
        handler: products-api
        middlewares:
          - cors
          - request-id
          - rate-limiter

      - method: "GET"
        path: "/api/products/{id}"
        handler: products-api
        middlewares:
          - cors
          - request-id
          - rate-limiter

      # Public: authentication
      - method: "POST"
        path: "/api/auth/login"
        handler: auth
        middlewares:
          - cors
          - request-id
          - rate-limiter

      - method: "POST"
        path: "/api/auth/register"
        handler: auth
        middlewares:
          - cors
          - request-id
          - rate-limiter

      # Protected: user profile (requires JWT)
      - method: "GET"
        path: "/api/auth/profile"
        handler: auth
        middlewares:
          - cors
          - request-id
          - rate-limiter
          - auth-middleware

      - method: "PUT"
        path: "/api/auth/profile"
        handler: auth
        middlewares:
          - cors
          - request-id
          - rate-limiter
          - auth-middleware

      # Protected: orders (requires JWT)
      - method: "POST"
        path: "/api/orders"
        handler: orders-api
        middlewares:
          - cors
          - request-id
          - rate-limiter
          - auth-middleware

      - method: "GET"
        path: "/api/orders"
        handler: orders-api
        middlewares:
          - cors
          - request-id
          - rate-limiter
          - auth-middleware

      - method: "GET"
        path: "/api/orders/{id}"
        handler: orders-api
        middlewares:
          - cors
          - request-id
          - rate-limiter
          - auth-middleware

  # Order state machine — 10-state production pipeline
  statemachine:
    engine: order-state
    resourceMappings:
      - resourceType: "orders"
        stateMachine: "order-state"
        instanceIDKey: "id"
    definitions:
      - name: order-processing
        description: "Production-realistic order processing pipeline"
        initialState: "new"
        states:
          new:
            description: "Order created, awaiting validation"
            isFinal: false
            isError: false
          validating:
            description: "Checking inventory availability"
            isFinal: false
            isError: false
          validated:
            description: "Inventory confirmed, ready for payment"
            isFinal: false
            isError: false
          paying:
            description: "Processing payment"
            isFinal: false
            isError: false
          paid:
            description: "Payment confirmed, ready for shipping"
            isFinal: false
            isError: false
          payment_failed:
            description: "Payment declined, may retry"
            isFinal: false
            isError: false
          shipping:
            description: "Generating shipping label"
            isFinal: false
            isError: false
          shipped:
            description: "Order shipped, in transit"
            isFinal: false
            isError: false
          ship_failed:
            description: "Shipping label generation failed, may retry"
            isFinal: false
            isError: false
          delivered:
            description: "Order delivered successfully"
            isFinal: true
            isError: false
          cancelled:
            description: "Order cancelled"
            isFinal: true
            isError: false
          failed:
            description: "Order processing failed permanently"
            isFinal: true
            isError: true
        transitions:
          # Validation pipeline
          start_validation:
            fromState: "new"
            toState: "validating"
          validation_passed:
            fromState: "validating"
            toState: "validated"
          validation_failed:
            fromState: "validating"
            toState: "failed"
          # Payment pipeline
          start_payment:
            fromState: "validated"
            toState: "paying"
            autoTransform: true
          payment_approved:
            fromState: "paying"
            toState: "paid"
          payment_declined:
            fromState: "paying"
            toState: "payment_failed"
          retry_payment:
            fromState: "payment_failed"
            toState: "paying"
          # Shipping pipeline
          start_shipping:
            fromState: "paid"
            toState: "shipping"
            autoTransform: true
          shipping_confirmed:
            fromState: "shipping"
            toState: "shipped"
          shipping_failed:
            fromState: "shipping"
            toState: "ship_failed"
          retry_shipping:
            fromState: "ship_failed"
            toState: "shipping"
          # Final transitions
          deliver_order:
            fromState: "shipped"
            toState: "delivered"
            autoTransform: true
          cancel_order:
            fromState: "new"
            toState: "cancelled"
          cancel_validated:
            fromState: "validated"
            toState: "cancelled"
    hooks:
      # When entering 'validating' state, run inventory check
      - workflowType: "order-processing"
        transitions: ["start_validation"]
        handler: "step-validate"
      # When entering 'paying' state, run payment processing
      - workflowType: "order-processing"
        transitions: ["start_payment"]
        handler: "step-payment"
      # When entering 'shipping' state, run shipping label generation
      - workflowType: "order-processing"
        transitions: ["start_shipping"]
        handler: "step-shipping"
      # Notify on all terminal and milestone states
      - workflowType: "order-processing"
        toStates: ["validated", "paid", "shipped", "delivered", "cancelled", "failed", "payment_failed", "ship_failed"]
        handler: "notification-handler"

  # Messaging subscriptions
  messaging:
    broker: event-broker
    subscriptions:
      - topic: "order.created"
        handler: notification-handler
      - topic: "order.validated"
        handler: notification-handler
      - topic: "order.paid"
        handler: notification-handler
      - topic: "order.shipped"
        handler: notification-handler
      - topic: "order.delivered"
        handler: notification-handler
      - topic: "order.cancelled"
        handler: notification-handler

# --- Triggers ---
# Triggers automatically chain the processing pipeline:
#   POST /api/orders -> start_validation
#   order.validated event -> start_payment
#   order.paid event -> start_shipping
triggers:
  http:
    routes:
      - path: "/api/orders"
        method: "POST"
        workflow: "order-processing"
        action: "start_validation"
  event:
    subscriptions:
      - topic: "order.validated"
        event: "order.validated"
        workflow: "order-processing"
        action: "start_payment"
      - topic: "order.paid"
        event: "order.paid"
        workflow: "order-processing"
        action: "start_shipping"
