openapi: "3.0.0"
info:
  title: Petstore API
  version: "1.0.0"
  description: A sample pet store API based on the OpenAPI 3.0 Petstore example

paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: A list of pets
        "400":
          description: Invalid request
    post:
      operationId: createPet
      summary: Create a pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                tag:
                  type: string
                  maxLength: 50
      responses:
        "201":
          description: Null response
        "400":
          description: Validation error

  /pets/{petId}:
    get:
      operationId: showPetById
      summary: Info for a specific pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Expected response to a valid request
        "404":
          description: Pet not found

  /pets/{petId}/status:
    put:
      operationId: updatePetStatus
      summary: Update pet status
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - available
                    - pending
                    - sold
      responses:
        "200":
          description: Updated
        "400":
          description: Invalid status
        "404":
          description: Pet not found
