Feature: State Machine Workflow Testing
  As a workflow developer
  I want to create and test state machine-based workflows
  So that I can build complex business process automation with state transitions

  Background:
    Given the workflow UI is running
    And I am logged in as an admin user

  Scenario: Create a basic order processing state machine
    When I create a state machine workflow with:
      | initialState | new |
      | states       | new,processing,completed,failed |
    Then the workflow should be created successfully
    And the workflow should use "statemachine.engine" module
    And the workflow should manage state transitions

  Scenario: Create user onboarding state machine workflow
    When I create a workflow with:
      | name        | User Onboarding State Machine |
      | description | Manages user onboarding process |
      | config      | modules:\n  - name: onboarding-engine\n    type: statemachine.engine\n  - name: state-tracker\n    type: state.tracker\n  - name: state-connector\n    type: state.connector\n\nworkflows:\n  statemachine:\n    engine: onboarding-engine\n    definitions:\n      - name: user-onboarding\n        initialState: "registered"\n        states:\n          registered:\n            description: "User has registered"\n            isFinal: false\n            isError: false\n          email_verified:\n            description: "Email verification completed"\n            isFinal: false\n            isError: false\n          profile_completed:\n            description: "User profile completed"\n            isFinal: false\n            isError: false\n          approved:\n            description: "User account approved"\n            isFinal: true\n            isError: false\n          rejected:\n            description: "User account rejected"\n            isFinal: true\n            isError: true\n        transitions:\n          verify_email:\n            fromState: "registered"\n            toState: "email_verified"\n          complete_profile:\n            fromState: "email_verified"\n            toState: "profile_completed"\n          approve_account:\n            fromState: "profile_completed"\n            toState: "approved"\n          reject_account:\n            fromState: "profile_completed"\n            toState: "rejected" |
    Then the workflow should be created successfully
    And the workflow should manage state transitions

  Scenario: Create order fulfillment state machine workflow
    When I create a workflow with:
      | name        | Order Fulfillment State Machine |
      | description | E-commerce order processing workflow |
      | config      | modules:\n  - name: order-engine\n    type: statemachine.engine\n  - name: order-tracker\n    type: state.tracker\n  - name: order-connector\n    type: state.connector\n  - name: payment-handler\n    type: messaging.handler\n  - name: fulfillment-handler\n    type: messaging.handler\n  - name: notification-handler\n    type: messaging.handler\n  - name: order-broker\n    type: messaging.broker\n\nworkflows:\n  statemachine:\n    engine: order-engine\n    definitions:\n      - name: order-workflow\n        initialState: "created"\n        states:\n          created:\n            description: "Order created"\n            isFinal: false\n            isError: false\n          payment_pending:\n            description: "Awaiting payment"\n            isFinal: false\n            isError: false\n          paid:\n            description: "Payment received"\n            isFinal: false\n            isError: false\n          shipped:\n            description: "Order shipped"\n            isFinal: false\n            isError: false\n          delivered:\n            description: "Order delivered"\n            isFinal: true\n            isError: false\n          cancelled:\n            description: "Order cancelled"\n            isFinal: true\n            isError: false\n          failed:\n            description: "Order failed"\n            isFinal: true\n            isError: true\n        transitions:\n          process_payment:\n            fromState: "created"\n            toState: "payment_pending"\n          payment_success:\n            fromState: "payment_pending"\n            toState: "paid"\n          ship_order:\n            fromState: "paid"\n            toState: "shipped"\n          deliver_order:\n            fromState: "shipped"\n            toState: "delivered"\n          cancel_order:\n            fromState: "created"\n            toState: "cancelled" |
    Then the workflow should be created successfully
    And the workflow should manage state transitions

  Scenario: Create loan approval state machine workflow
    When I create a workflow with:
      | name        | Loan Approval State Machine |
      | description | Bank loan approval process |
      | config      | modules:\n  - name: loan-engine\n    type: statemachine.engine\n  - name: loan-tracker\n    type: state.tracker\n  - name: credit-check-handler\n    type: messaging.handler\n  - name: underwriting-handler\n    type: messaging.handler\n  - name: approval-handler\n    type: messaging.handler\n  - name: loan-broker\n    type: messaging.broker\n\nworkflows:\n  statemachine:\n    engine: loan-engine\n    definitions:\n      - name: loan-approval\n        initialState: "application_submitted"\n        states:\n          application_submitted:\n            description: "Loan application submitted"\n            isFinal: false\n            isError: false\n          document_review:\n            description: "Documents under review"\n            isFinal: false\n            isError: false\n          credit_check:\n            description: "Credit check in progress"\n            isFinal: false\n            isError: false\n          underwriting:\n            description: "Underwriting review"\n            isFinal: false\n            isError: false\n          approved:\n            description: "Loan approved"\n            isFinal: true\n            isError: false\n          rejected:\n            description: "Loan rejected"\n            isFinal: true\n            isError: true\n          cancelled:\n            description: "Application cancelled"\n            isFinal: true\n            isError: false\n        transitions:\n          start_review:\n            fromState: "application_submitted"\n            toState: "document_review"\n          start_credit_check:\n            fromState: "document_review"\n            toState: "credit_check"\n          start_underwriting:\n            fromState: "credit_check"\n            toState: "underwriting"\n          approve_loan:\n            fromState: "underwriting"\n            toState: "approved"\n          reject_loan:\n            fromState: "underwriting"\n            toState: "rejected" |
    Then the workflow should be created successfully
    And the workflow should manage state transitions

  Scenario: Create incident management state machine workflow
    When I create a workflow with:
      | name        | Incident Management State Machine |
      | description | IT incident management workflow |
      | config      | modules:\n  - name: incident-engine\n    type: statemachine.engine\n  - name: incident-tracker\n    type: state.tracker\n  - name: triage-handler\n    type: messaging.handler\n  - name: assignment-handler\n    type: messaging.handler\n  - name: resolution-handler\n    type: messaging.handler\n  - name: incident-broker\n    type: messaging.broker\n\nworkflows:\n  statemachine:\n    engine: incident-engine\n    definitions:\n      - name: incident-management\n        initialState: "reported"\n        states:\n          reported:\n            description: "Incident reported"\n            isFinal: false\n            isError: false\n          triaged:\n            description: "Incident triaged"\n            isFinal: false\n            isError: false\n          assigned:\n            description: "Incident assigned to team"\n            isFinal: false\n            isError: false\n          in_progress:\n            description: "Work in progress"\n            isFinal: false\n            isError: false\n          resolved:\n            description: "Incident resolved"\n            isFinal: false\n            isError: false\n          closed:\n            description: "Incident closed"\n            isFinal: true\n            isError: false\n          escalated:\n            description: "Incident escalated"\n            isFinal: false\n            isError: false\n        transitions:\n          triage:\n            fromState: "reported"\n            toState: "triaged"\n          assign:\n            fromState: "triaged"\n            toState: "assigned"\n          start_work:\n            fromState: "assigned"\n            toState: "in_progress"\n          resolve:\n            fromState: "in_progress"\n            toState: "resolved"\n          close:\n            fromState: "resolved"\n            toState: "closed"\n          escalate:\n            fromState: "assigned"\n            toState: "escalated" |
    Then the workflow should be created successfully
    And the workflow should manage state transitions

  Scenario: Create document approval state machine workflow
    When I create a workflow with:
      | name        | Document Approval State Machine |
      | description | Document review and approval process |
      | config      | modules:\n  - name: document-engine\n    type: statemachine.engine\n  - name: document-tracker\n    type: state.tracker\n  - name: review-handler\n    type: messaging.handler\n  - name: approval-handler\n    type: messaging.handler\n  - name: document-broker\n    type: messaging.broker\n\nworkflows:\n  statemachine:\n    engine: document-engine\n    definitions:\n      - name: document-approval\n        initialState: "draft"\n        states:\n          draft:\n            description: "Document in draft"\n            isFinal: false\n            isError: false\n          submitted:\n            description: "Document submitted for review"\n            isFinal: false\n            isError: false\n          under_review:\n            description: "Document under review"\n            isFinal: false\n            isError: false\n          changes_requested:\n            description: "Changes requested"\n            isFinal: false\n            isError: false\n          approved:\n            description: "Document approved"\n            isFinal: true\n            isError: false\n          rejected:\n            description: "Document rejected"\n            isFinal: true\n            isError: true\n        transitions:\n          submit:\n            fromState: "draft"\n            toState: "submitted"\n          start_review:\n            fromState: "submitted"\n            toState: "under_review"\n          request_changes:\n            fromState: "under_review"\n            toState: "changes_requested"\n          approve:\n            fromState: "under_review"\n            toState: "approved"\n          reject:\n            fromState: "under_review"\n            toState: "rejected"\n          resubmit:\n            fromState: "changes_requested"\n            toState: "submitted" |
    Then the workflow should be created successfully
    And the workflow should manage state transitions