name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test config package
      run: go test -v ./config/...
      
    - name: Test module package
      run: go test -v ./module/...